documentation/ProjectStructure.mdx
The spark project has the following structure:
- `.storybook/`: The storybook configuration directory for launching the tool.
- `bin/`: All the needed scripts for the project will be included in it.
- `documentation/`: MDX files tracked by storybook for documenting the Design System.
- `assets/`: All the necessary assets needed for the documentation directory _MUST_ be placed inside.
- `foundations/`: Theming guidelines: Colors, Spacings, Typographies, ...
- `patterns/`: Standards on how to solve common design problems.
- `principles/`: Guidelines on how to design & implement software.
- `practices/`: Useful tactics for being an effective developer.
- `packages/`: This directory is tracked by lerna. All the pills inside of it will be published as packages and _MUST_ follow the [following …
=> docs(root):  ADD project structure

package.json
Make sure git hooks enabled after install as husky suggests in step 3 in manual installation
https://typicode.github.io/husky/#/?id=automatic-recommended
Thanks @acd02 for the heads up
=> chore: to automatically have Git hooks enabled after install

.github/workflows/quality.yml
Enable designers and QA analyst to check quickly in every PR the visual changes made on any component.
**TASK**: #128 
Add Chromatic deployment step to have visual testing in quality.yml
- [x ] 🛠️ Tool
=> ci: add Chromatic deployment step

documentation/contributing/CommitStrategy.mdx, documentation/contributing/TestingStrategy.mdx, documentation/practices/Naming.mdx
Some proofreading on two documentation files:
- commit
- testing
As a reminder, we are now using American English as a reference.
=> docs: fix typos in the contribution docs

documentation/build/Build.mdx, documentation/contributing/CommitStrategy.mdx, documentation/contributing/TestingStrategy.mdx, documentation/contributing/WritingStories.mdx, documentation/contributing/code-of-conduct/JudgmentAndDecisionMaking.mdx, documentation/definitions/PackageStructure.mdx, documentation/definitions/ProjectStructure.mdx, documentation/practices/Naming.mdx, packages/hooks/use-mounted-state/src/useMountedState.stories.mdx, packages/utils/theme/src/index.stories.mdx
Some proofreading on the documentation written so far:
=> docs: fix typos

package-lock.json, packages/utils/cli/bin/spark-setup-theme.mjs, packages/utils/cli/bin/spark.mjs, packages/utils/cli/package.json
#253
Add new cli command "spark setup-theme" to simplify theme configuration setup for Spark design system users.
=> feat(cli-utils): add new "spark setup-theme" cli command

documentation/contributing/TestingStrategy.mdx, documentation/helpers/StoryStatus/index.tsx, package-lock.json, package.json, tailwind.config.cjs
**TASK**: #269 
Because we use ship/show/ask, some documentation might be merged into the `main` branch without validation. I suggest we flag those as "draft" documentation until we validate it together at some point.
(It was also a way to test our new color tokens)
=> docs: story status component for draft and deprecated docs

package-lock.json, packages/utils/cli/bin/spark-setup-themes.mjs, packages/utils/cli/src/setup-themes/utils/createCSSTokenfile.js, packages/utils/cli/src/setup-themes/utils/utils.js, packages/utils/theme/src/types.ts
=> feat: enhance our theme building process by implementing support for various base font sizes

CONTRIBUTING.md
Change `npm run install` to `npm install` in [CONTRIBUTING.md](https://github.com/adevinta/spark/blob/main/CONTRIBUTING.md)
=> docs: fix install command in CONTRIBUTING.md

package-lock.json, packages/components/button/package.json, packages/components/button/src/Button.doc.mdx, packages/components/button/src/Button.stories.tsx, packages/components/button/src/Button.test.tsx, packages/components/button/src/Button.tsx, packages/components/radio/src/Radio.test.tsx, packages/components/slot/src/Slot.stories.tsx, packages/components/slot/src/Slot.test.tsx, packages/components/slot/src/Slot.tsx, packages/components/slot/src/index.ts
**TASK**: #445 
This PR:
- Add the possibility of using the button as a link
- Update some tests to follow the guidelines
- Update `Slot` props definition to match the radix ones
- Add `Slot` missing `forwardRef`. Thanks @Powerplex for spotting this out
=> 445 components add link option for button component

documentation/practices/ComponentDoD.mdx, documentation/practices/ComponentDoR.mdx
**TASK**: #409 
Add documentation for how our tasks (user stories) will be defined before we start to work on them.
=> DOCS: add definition of ready documentation

.storybook/main.cjs, .storybook/preview-head.html, .storybook/preview.cjs, .storybook/sb-theming.css, package-lock.json, package.json
**TASK**: #486 
Spark having 2 themes (light and dark), I used the recently reeleased storybook addon for theme management to preview it inside both Docs and CSF stories: https://storybook.js.org/blog/styling-addon-configure-styles-and-themes-in-storybook/
https://user-images.githubusercontent.com/2033710/228315799-fa565147-2962-47cd-ab85-305581dd552e.mov
=> feat: enabled dark theme preview for components

.github/workflows/quality.yml, .storybook/main.cjs, package-lock.json, package.json
As proposed by @Powerplex, this PR enables turbosnap for Chromatic so that we only test the changed stories.
A `preview-stats.json` is needed by turbosnap. This file is generated by [vite-plugin-turbosnap](https://github.com/IanVS/vite-plugin-turbosnap).
- [ x] 🛠️ Tool
=> ci: enable turbosnap for Chromatic

package.json, packages/components/button/src/variants/contrast.ts, packages/components/button/src/variants/ghost.ts, packages/components/button/src/variants/outlined.ts, packages/components/button/src/variants/tinted.ts
The previous glob pattern was incorrect 🤦, which prevented the files from being properly linted. This fix updates the ESLint glob pattern to ensure that all relevant files are now correctly linted
-->
=> fix: eslint glob

package-lock.json, packages/components/button/package.json, packages/components/button/src/variants/contrast.ts, packages/components/button/src/variants/default.ts, packages/components/button/src/variants/filled.ts, packages/components/button/src/variants/ghost.ts, packages/components/button/src/variants/outlined.ts, packages/components/button/src/variants/tinted.ts, packages/components/switch/package.json, packages/components/switch/src/Switch.variants.tsx
Use the `tw` function from the `internal-utils` package to avoid duplicating the same function across multiple locations in the codebase.
- [] 🛠️ Tool
-->
=> refactor: use tw from internal-utils package

package-lock.json, packages/components/switch/src/Switch.variants.tsx, packages/components/tag/package.json, packages/utils/theme/src/defaultTheme.ts, packages/utils/theme/src/types.ts
**TASK**: #502 
Decoupled shadow tokens from tailwind's default tokens.
Specs: https://zeroheight.com/1186e1705/p/39675a-elevation
=> feat(theme-utils): setup shadow tokens

.storybook/preview-head.html, package-lock.json, packages/components/button/src/Button.stories.tsx, packages/utils/theme/src/defaultTheme.ts, packages/utils/theme/src/types.ts
**TASK**: #523 
Setup Nunito font family tokens.
Setup nuni font family for stories previews (components).
=> docs: setup nunito font in storybook previews

packages/components/switch/src/Switch.variants.tsx
**TASK**: #532 
This PR remove the hover ring when the switch is disabled
=> fix(switch): hover with disable state

documentation/contributing/WritingStories.mdx, package-lock.json, packages/components/button/src/Button.doc.mdx, packages/components/checkbox/src/Checkbox.doc.mdx, packages/components/icon/src/Icon.doc.mdx, packages/components/portal/src/Portal.doc.mdx, packages/components/radio/src/Radio.doc.mdx, packages/components/slot/src/Slot.doc.mdx, packages/components/switch/src/Switch.doc.mdx, packages/components/tag/src/Tag.doc.mdx, packages/components/visually-hidden/src/VisuallyHidden.doc.mdx, packages/utils/cli/src/generate/templates/component/src/[Component.doc.mdx].js, packages/utils/cli/src/generate/templates/component/src/[Component.stories.tsx].js, packages/utils/cli/src/generate/templates/hook/src/[name.stories.mdx].js
**TASK**: #552 
V7 of storybook deprecated `ArgsTable`. We should use `ArgTypes` instead.
Unfortunately this means that it's no longer compatible for compound components. I have a solution for that that requires us to merge our Tabs package first (future PR).
=> docs: deprecated ArgsTable with V7 of storybook

packages/components/button/package.json, packages/components/checkbox/package.json, packages/components/icon/package.json, packages/components/radio/package.json, packages/components/slot/package.json, packages/components/switch/package.json, packages/components/tag/package.json, packages/components/visually-hidden/package.json, packages/hooks/use-combined-state/package.json, packages/utils/tailwind-plugins/package.json, packages/utils/theme/package.json
This PR aims to update all dependencies across our monorepo packages to use caret (^) versions instead of fixed versions. By harmonizing the versions of shared dependencies, we can ensure that they will be deduped when consumed
=> feat: harmonize dependency versions using carets

package-lock.json, packages/components/switch/package.json, packages/components/switch/src/Switch.doc.mdx, packages/components/switch/src/Switch.stories.tsx, packages/components/switch/src/Switch.tsx, packages/components/switch/src/SwitchInput.styles.ts, packages/components/switch/src/SwitchInput.tsx, packages/hooks/use-combined-state/src/useCombinedState.tsx
**TASK**: #618 
Following specs review session, it seems some features needed to be added:
- icon removal
- icon customization
- controlled mode demo
As well as two others that we need to discuss before merging:
=> feat(switch): customisable icons for switch, controlled mode

packages/components/radio/src/Radio.stories.tsx, packages/components/radio/src/RadioGroup.tsx
**TASK**: #617 
Manage orientations (horizontal/vertical) for RadioGroup component.
=> feat(radio): radioGroup orientation prop

documentation/practices/ComponentDoD.mdx
**TASK**: #664 
We already agreed that Spark components must allow outside style customization using tailwindcss classes, but it was not yet written in the Definition of Done.
=> docs: added className customization agreement to DoD

packages/components/button/src/Button.doc.mdx, packages/components/button/src/Button.stories.tsx, packages/components/button/src/Button.styles.tsx
**TASK**: #540 
This PR:
- Add a example of how icons could be added to a button (left, right and both)
=> docs(button): add left and right icons example

packages/utils/theme/src/defaultTheme.ts, packages/utils/theme/src/defaultThemeDark.ts, packages/utils/theme/src/types.ts
**TASK**: #675 
Figma update. Color tokens for background states no longer exists: https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?node-id=10-2165&t=Zs7JRNvRtWAb3wAD-4
=> feat(theme-utils): removed background colors state tokens

packages/components/button/src/Button.stories.tsx, packages/components/checkbox/src/CheckboxInput.tsx, packages/components/switch/src/Switch.stories.tsx, packages/components/switch/src/SwitchInput.tsx, packages/components/visually-hidden/src/VisuallyHidden.stories.tsx, packages/components/visually-hidden/src/VisuallyHidden.test.tsx, vite.config.ts
**TASK**: Nona
This PR fix storybook by importing icons in a isolated way
=> Fix storybook build

packages/components/checkbox/src/Checkbox.stories.tsx, packages/components/checkbox/src/CheckboxInput.styles.ts
=> feat(checkbox): add neutral and info intents

package-lock.json, packages/components/tabs/src/Tabs.test.tsx, packages/components/tabs/src/TabsTrigger.tsx
**TASK**: #744 
We (I, mostly...) missed to manage the tab item focus on overflowing content. Just needed a little scroll to it!
=> fix(tabs): add scroll to focused tab element

packages/components/icon/src/Icon.stories.tsx, packages/components/icon/src/Icon.styles.tsx, packages/utils/internal-utils/src/variants/constants.ts
**TASK**: #747 
New `xl` size added to specs: https://spark.adevinta.com/1186e1705/p/11373f-icon/b/80bf01/t/5734fc
=> feat(icon): added xl size for icon package

package-lock.json, packages/components/checkbox/package.json, packages/components/checkbox/src/CheckboxIndicator.tsx, packages/components/checkbox/src/CheckboxInput.styles.ts, packages/components/checkbox/src/CheckboxInput.tsx, packages/components/icon/src/Icon.tsx
**TASK**: #801 
This PR fixes an issue where checked icon is not visible in Safari
Before
After
=> 801 checkbox icon not visible in safari

packages/components/badge/src/Badge.doc.mdx, packages/components/button/src/Button.doc.mdx, packages/components/checkbox/src/Checkbox.doc.mdx, packages/components/icon-button/src/IconButton.doc.mdx, packages/components/label/src/Label.doc.mdx, packages/components/radio/src/Radio.doc.mdx, packages/components/switch/src/Switch.doc.mdx, packages/components/tabs/src/Tabs.doc.mdx, packages/components/visually-hidden/src/VisuallyHidden.doc.mdx
**TASK**: #810
There had been an agreement about accessibility documentation: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs#6-accessibility But we missed it! So we should add these sections on each story +1
=> docs: add missing accessibility details on storybook

package-lock.json, packages/components/switch/package.json, packages/components/switch/src/Switch.doc.mdx, packages/components/switch/src/Switch.stories.tsx, packages/components/switch/src/Switch.test.tsx, packages/components/switch/src/Switch.tsx, packages/components/switch/src/SwitchInput.tsx, packages/components/switch/src/SwitchLabel.tsx
**TASK**: #734 
We now want to enable the usage of `FormField` with our form components, to improve field state management and so.
=> feat(switch): allowing formfield usage for switch component

packages/utils/tailwind-plugins/package.json
The Utility package for Tailwind has a pinned dependency on the exact major of TailwindCSS, which is restrictive for a consumer. If there is no limiting issue, and given how liberally SemVer is used in the JS world, I propose to pin only to the major and allow consumers to upgrade.
=> refactor: widen the Tailwind peerDep for utils

.eslintrc.cjs, packages/components/checkbox/src/Checkbox.test.tsx, packages/components/checkbox/src/Checkbox.tsx, packages/components/form-field/src/FormField.test.tsx, packages/components/icons/src/index.test.tsx, packages/components/input/src/Input.test.tsx, packages/components/popover/src/PopoverContent.styles.ts, packages/components/radio/src/Radio.test.tsx, packages/components/slot/src/Slot.stories.tsx, packages/components/switch/src/Switch.test.tsx, packages/components/switch/src/SwitchInput.tsx, packages/components/tabs/src/Tabs.test.tsx, packages/components/tabs/src/TabsList.tsx, packages/components/tabs/src/useResizeObserver.test.ts, packages/utils/internal-utils/src/variants/index.ts, packages/utils/tailwind-plugins/spark-theme/getCSSVariableReferences.js, packages/utils/tailwind-plugins/spark-theme/hexRgb.js
**TASK**: #844
In our codebase, there are several ESLint ignore comments that have been added to disable specific rules or warnings. These comments can make it harder to maintain and understand the codebase over time.
This PR remove these comments and instead address the underlying issues they are suppressing.
=> remove eslint ignore comments

package-lock.json, packages/components/button/src/Button.styles.tsx
**TASK**: #830 
To improve our DS consistency, we want to harmonize border sizes. As visible in [Figma specs](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=2340-22556&t=xkErzPSGZ3TXhuHG-0), we now want Button and IconButton components to have a 1px border size.
=> refactor(button): upd outlined variant border size

package-lock.json, packages/components/radio/package.json, packages/components/radio/src/Radio.doc.mdx, packages/components/radio/src/Radio.stories.tsx, packages/components/radio/src/Radio.test.tsx, packages/components/radio/src/Radio.tsx, packages/components/radio/src/RadioLabel.styles.tsx, packages/components/radio/src/RadioLabel.tsx
**TASK**: #798 
With current DOM structure (label tag wrapping the whole content) we recently noticed a small accessibility concern, about accessible name.
Indeed, the component itself doesn't have any accessible name. This is due to component text (aka children) added as a sibling DOM node, and so not directly related. This can be confirmed using the "Axe" Chrome accessibility extension, and testing the component.
After discussions with @andresz1, @acd02 and @Powerplex we agreed:
- changing the DOM structure, to match the Radix pattern: having the label as a sibling, linked through an `htmlFor` attribute. The whole content wrapped within a neutral div, for ex.
- using `aria-label` or `aria-labelledby` based on use case
**Before:**
**After:**
=> fix(radio): fix and improve a11y on radio

tailwind.config.viewer.cjs
**TASK**: #860
The theme token keys that were in all uppercase letters were not handled properly. As a result, they were not displaying correctly on our Tailwind Config Viewer website.
=> fix: update TCV config file to include uppercased string edge cases

package-lock.json, packages/components/tag/src/Tag.doc.mdx, packages/components/tag/src/Tag.stories.tsx, packages/components/tag/src/Tag.styles.tsx
#913 
Design updates to be synced with Figma: https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?type=design&node-id=14-3762&t=yL9keRLExfQd0LlZ-4
- outline border goes from 2px to 1px width.
- outline background color goes from `transparent` to `surface`
=> style(tag): synced styles with figma for outlined design

packages/components/form-field/src/index.ts, packages/components/label/src/index.ts, packages/components/radio-group/src/index.ts, packages/components/tabs/src/Tabs.tsx
**TASK**: #911 
For some compound components Canvas block snippets were not using proper `displayName`.
=> fix: code snippets on component docs

documentation/helpers/ArgTypes/index.tsx, packages/components/form-field/src/FormField.doc.mdx, packages/components/input/src/Input.doc.mdx, packages/components/label/src/Label.doc.mdx, packages/components/popover/src/Popover.doc.mdx, packages/components/radio-group/src/RadioGroup.doc.mdx, packages/components/tabs/src/Tabs.doc.mdx
**TASK**: #941 
Feedback from a feature team trying to use Form components (TextField, etc) is that it's not clear what is the role of each subComponent. I was thinking we could start by adding description in the argTypes table for each subComponent to make it more clear.
=> docs: enable description for subComponents tables

packages/components/button/src/variants/contrast.ts, packages/components/button/src/variants/filled.ts, packages/components/button/src/variants/ghost.ts, packages/components/button/src/variants/outlined.ts, packages/components/button/src/variants/tinted.ts
**TASK**: #950
Fix hover styles not being applied correctly when using the 'asChild' prop on Button due to ":enabled" [pseudo-class](https://html.spec.whatwg.org/multipage/semantics-other.html#selector-enabled) not working with child divs or "a" tags
=> fix(button): fix hover styles not being applied correctly when using the 'asChild' prop on button

documentation/helpers/FAQ/Question.tsx
Add IDs to FAQ helper items for easier URL sharing and navigation
**TASK**: #964
improve the FAQ helper component by adding an ID to each item. This will allow users to share a URL and go (scroll) straight to the desired question.
=> docs: add ids to faq helper items for easier url sharing and navigation

packages/components/button/src/Button.styles.tsx, packages/utils/internal-utils/src/variants/constants.ts
**TASK**: 
The chip designs add a new one not included in out internal-util constants. I added that NEW 'dashed' design and pick the right values in the button to filter that undesired design value.
=> feat(internal-utils): add dashed design to internal utils constants

packages/components/checkbox/src/CheckboxGroup.styles.ts, packages/components/checkbox/src/CheckboxInput.styles.ts
**TASK**: #975 
After reviewing Design specs it appeared that Checkbox size wasn't compliant. We want to fix this.
=> style(checkbox): resync sizing according to design specs

packages/components/radio-group/src/Radio.tsx, packages/components/radio-group/src/RadioGroup.doc.mdx, packages/components/radio-group/src/RadioGroup.stories.tsx, packages/components/radio-group/src/RadioGroup.styles.ts, packages/components/radio-group/src/RadioGroup.tsx, packages/components/radio-group/src/RadioGroupContext.tsx, packages/components/radio-group/src/RadioGroupProvider.tsx, packages/components/radio-group/src/RadioIndicator.styles.ts, packages/components/radio-group/src/RadioIndicator.tsx, packages/components/radio-group/src/RadioInput.styles.ts, packages/components/radio-group/src/RadioInput.tsx
**TASK**: #976 
After reviewing Design specs it appeared that RadioGroup sizes weren't compliant. We want to fix this, and also to remove the prop (as there should be only one size).
=> style(radio-group): resync according to design specs

documentation/helpers/FAQ/Answer.tsx, documentation/helpers/FAQ/Item.tsx, documentation/helpers/FAQ/Question.tsx, documentation/helpers/FAQ/context.tsx
**TASK**: #1018
Update the FAQ component to include a height transition when opening and closing items, to provide a smoother user experience
=> feat: add height transition to FAQ component

packages/components/input/package.json, packages/components/input/src/InputClearButton.tsx
**TASK**: #1036 
This PR:
- Change `InputGroup.ClearButton` to be a custom one
- Clickable area improvement (smaller in mobile but it takes full height)
=> 1036 components input clear button styles update

documentation/helpers/ArgTypes/index.tsx, package-lock.json, packages/components/form-field/src/FormField.doc.mdx, packages/components/input/src/Input.doc.mdx
**TASK**: #1045 
- fixed typo in Install section of `FormField` (it said "form-control")
- added missing `FormField.ClearButton` to the `FormField` props table
- added description to each component of the `FormField` compound
- added description to each component of the `Input` compound
https://github.com/adevinta/spark/assets/2033710/8a0f25df-2aa8-4dba-968b-d0c5822eb509
=> Fix formfield doc typo

package-lock.json, packages/components/input/src/Input.doc.mdx, packages/components/input/src/Input.stories.tsx, packages/components/input/src/Input.styles.ts, packages/components/input/src/Input.tsx, packages/components/input/src/InputAddon.styles.ts, packages/components/input/src/InputAddon.tsx, packages/components/input/src/InputClearButton.tsx, packages/components/input/src/InputGroup.styles.ts, packages/components/input/src/InputIcon.tsx, packages/components/input/src/InputLeadingAddon.tsx, packages/components/input/src/InputTrailingAddon.tsx
**TASK**: #1034 
Disabled styles for `Input` and `InputGroup`.
Styles are applied on the input, as well as its addons and icons.
Styles is different depending on the type of (addon: raw text, solid, inline)
https://github.com/adevinta/spark/assets/2033710/10c4ded7-a9b3-45f6-afca-a7511b7d011e
=> feat(input): disabled input styles

packages/components/checkbox/src/Checkbox.doc.mdx, packages/components/checkbox/src/Checkbox.stories.tsx, packages/components/radio-group/src/RadioGroup.doc.mdx, packages/components/radio-group/src/RadioGroup.stories.tsx
**TASK**: #1040
Add an implementation of a custom checkbox component to the documentation that can provide guidance to developers who need to implement a custom checkbox / radio group
=> docs(checkbox/radio group): add implementation and guidance for custom checkbox/radio group components

package-lock.json, packages/components/checkbox/package.json, packages/components/input/package.json, packages/components/radio-group/package.json, packages/components/switch/package.json
`FormField`version has not been updated properly in dependant packages.
=> fix: updating deprecated formField versions

.github/workflows/quality.yml
**TASK**: 
This change will able the possibility to have CI process in the PR's that triggers a canary branch
- 1st Create canary branch on server
`canary/[whatever]`
- 2nd Create a new branch comming from the canary
`canary/[whatever]-stage-[number]`
-  3rd Create a Pr from canary stage to canary branch
All PR's triggering a `canary/**` brach name will fire the Quality CI process
=> ci: add canary branches passing the CI

package-lock.json, packages/components/checkbox/src/Checkbox.stories.tsx, packages/components/icons/src/index.stories.tsx
`icons` and `checkbox` were at the end of the components in the sidebar instead of being alphabetically sorted.
Before
After
=> docs: component alphabetical order fix

packages/utils/theme/src/defaultTheme.ts, packages/utils/theme/src/defaultThemeDark.ts, packages/utils/theme/src/types.ts
**TASK**: #1073 
Add "basic" and "accents" color tokens to the Spark theme's color structure
=> feat(theme-utils): add "basic" and "accents" color tokens to the Spark theme's color structure

packages/components/form-field/src/FormField.test.tsx, packages/components/form-field/src/FormFieldCharactersCount.tsx
`FormField.CharactersCount`: The component throws and error when `value` prop is `undefined`.
=> fix(form-field): fix undefined values when accessing length property

.eslintrc.cjs, packages/components/icons/scripts/build.mjs, packages/components/icons/scripts/utils/componentize.mjs, packages/components/icons/scripts/utils/indexify.mjs, packages/components/icons/scripts/utils/tagify.mjs, packages/components/icons/scripts/utils/writeFile.mjs, packages/components/popover/src/PopoverHeader.tsx, packages/components/radio-group/src/RadioGroup.tsx, packages/components/switch/src/Switch.tsx, packages/utils/cli/src/generate/generators/TemplateGenerator.mjs, packages/utils/cli/src/generate/templates/component/src/[Component.stories.tsx].js, packages/utils/cli/src/generate/templates/component/src/[Component.styles.ts].js, packages/utils/cli/src/generate/templates/component/src/[Component.styles.tsx].js, packages/utils/cli/src/generate/validators/NameValidator.mjs, packages/utils/cli/test/spark-generate.test.ts, packages/utils/tailwind-plugins/animations/index.js, packages/utils/tailwind-plugins/utilities/index.js, packages/utils/tailwind-plugins/variants/index.js
**TASK**: #1110 
We initially turned off the ESLint rule for unused vars. This lead some issues we want to fix.
Most of changes should have minimal impact, but in some cases we should check that everything still works as expected (ex. when declared props weren't used within a component):
- `PopoverHeader`
- `RadioGroup`
- `Switch`
=> refactor: update eslint rules for unused vars

packages/components/checkbox/src/Checkbox.tsx
**TASK**: #1115 
This PR fixes an issue in the Checkbox component that when the id is set it wasn't being linked to the label
=> fix(checkbox): id not being link to label

packages/components/dialog/src/Dialog.doc.mdx, packages/components/dialog/src/Dialog.stories.tsx, packages/components/dialog/src/Dialog.tsx, packages/components/dialog/src/DialogBody.tsx, packages/components/dialog/src/DialogContent.styles.tsx, packages/components/dialog/src/DialogContent.tsx, packages/components/dialog/src/DialogFooter.tsx, packages/components/dialog/src/DialogHeader.tsx, packages/components/dialog/src/index.ts
**TASK**: #1101 
- added `Dialog.Header` (sticky)
- added `Dialog.Body` (scrollable when content overflows)
- added `Dialog.Footer` (sticky)
a11y: 
- This [Axe rule](https://dequeuniversity.com/rules/axe/4.7/scrollable-region-focusable?application=AxeChrome) is saying that the body must be focusable or have a focusable child in order to be scrollable using the keyboard (Space or Shift + Space)
https://github.com/adevinta/spark/assets/2033710/e50027e2-0b21-44d2-91c1-b243160064ad
=> feat(dialog): header footer and body behaviour

.storybook/preview-head.html, package-lock.json, packages/components/dialog/src/Dialog.doc.mdx, packages/components/dialog/src/Dialog.stories.tsx, packages/components/dialog/src/DialogContent.styles.tsx, packages/components/dialog/src/DialogTitle.tsx
- use of `inset` to position fullscreen `dialog`
- added story to display `sizes`
- fixed global sb styles interfering with our components styles in stories
=> style(dialog): fixed fullscreen size and title styles

documentation/contributing/writing-packages/WritingStories.mdx, package-lock.json, packages/components/input/src/Input.doc.mdx, packages/components/input/src/Input.stories.tsx
During the sharing session this morning we agreed on updating the guidelines on how to sort/order the stories in a cohesive way across component.
Here is the proposal with the adapted "Input" (other components will be updated in separate PRs)
=> docs: new agreement for stories order

package-lock.json, packages/components/form-field/src/FormFieldHelperMessage.tsx
**TASK**: #1182 
The token used for HelperMessage is incorrect and needs to be updated:
❌ now 👉 `text-neutral`
✅ needs to be updated to 👉 `text-on-surface/dim1`
=> style(form-field): upd helper message styles

.storybook/preview-head.html, documentation/helpers/ToC/index.tsx
**TASK**: #1243 
Fix main content layout issues to prevent horizontal scrolling caused by overflowing content
**before:**
**after:**
=> fix: main content layout issues

documentation/helpers/ArgTypes/index.tsx, package-lock.json
I know SB is not aimed to be used a lot on mobile, but this bug also happened on smaller screens or when we have the console opened.
Our `ArgTypes` component was in `vertical` orientation even on smaller screens, meaning we don't have much room to display the content (when the sidebar is still rendered).
https://github.com/adevinta/spark/assets/2033710/eb8e1cb5-d7cc-4a45-a260-0caab579b3e1
=> docs: adapted custom ArgTypes table for mobile screens

packages/components/popover/src/PopoverTrigger.tsx
**TASK**: #1276 
Using `forwardRef` without exploiting the `ref` argument throws a react warning in the console/terminal.
=> fix(popover): popover trigger was using forwardRef without ref

package-lock.json, packages/components/input/src/index.ts
**TASK**: #1282 
Developers told us that displayNames are missing in the documentation.
Before:
After:
=> docs(input): fix displayNames broken in sb source

package-lock.json, packages/components/badge/src/Badge.doc.mdx, packages/components/badge/src/Badge.stories.tsx, packages/components/badge/src/BadgeItem.styles.tsx
**TASK**: #1240
- Updated docs to match latest agreements: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs
- Updated `Badge` styles: no longer has an outline when used as standalone.
=> fix(badge): do not display outline when badge is standalone

packages/components/button/src/Button.stories.tsx, packages/components/button/src/Button.test.tsx, packages/components/button/src/Button.tsx, packages/components/spinner/src/index.ts
**TASK**: #1256 
Button loading state was previously linked to a disabled state. This caused focus loss that we don't want here. So we will update implementation using `aria-busy` attribute instead.
=> refactor(button): improv. loading state focus management

packages/components/input/src/Input.test.tsx, packages/components/input/src/Input.tsx, packages/components/input/src/InputGroup.tsx
**TASK**: #1255 
This PR:
- Fix `readOnly` not being propagated to standalone `Input` when used within `FormField`
- Fix `disabled` not being propagated to standalone `Input` when used within `FormField`
- Add tests
=> fix(input): readOnly and disabled within form field not being propagated

packages/components/checkbox/src/CheckboxInput.tsx, packages/components/radio-group/src/RadioGroup.tsx, packages/components/radio-group/src/RadioInput.tsx
**TASK**: #1320 
**RadioGroup:**
- remove misleading `onChange` prop from types as it is not actually supported
**Checkbox:**
- remove misleading `onChange` prop from types as it is not actually supported
=> feat: remove misleading onChange prop on some components

packages/utils/theme/src/defaultTheme.ts, packages/utils/theme/src/defaultThemeDark.ts, packages/utils/theme/src/types.ts
🚨 BREAKING CHANGE: remove outline-related tokens from our Theme interface
**TASK**: #1351
Remove outline-related tokens from our Theme interface
=> feat(theme-utils): remove outline-related tokens from our Theme interface

.github/workflows/pr-icon-update.yml, packages/components/icons/scripts/build.mjs
This PR adds a GitHub action to re-generate the icon set every time a PR is sent from the `spark-tokens` repo.
=> chore(icons): add github action to open a PR with updated icons

.github/workflows/pr-icon-update.yml
This PR resolves the issue with the new GitHub action responsible for opening a PR and building icons with every update from `spark-tokens`. We've renamed the action and included the necessary GitHub token to establish a connection with GitHub CLI.
=> chore(icons): fix github action

packages/components/dialog/src/DialogContent.styles.tsx
whenever a focused element inside the Dialod disappear, focus is forwarded to the Dialog.Content instead (a11y)
https://github.com/adevinta/spark/assets/2033710/71f40063-800d-46b3-90fa-3bd80f8ff572
=> fix(dialog): improved focus styles when focusable children disappear

packages/components/icon-button/src/IconButton.styles.tsx
**TASK**: #1427
The icon size for small IconButtons should be 16x16, but was currently set to 12x12
=> fix(icon-button): update small IconButton icon size to 16x16

package-lock.json, packages/components/form-field/src/FormFieldCharactersCount.tsx
**TASK**: #1451 
Rendered value of `CharactersCount` is rendered as 3 distinct text nodes in the HTML, making it difficult to parse or use in unit tests.
BEFORE
AFTER
=> fix(form-field): improved render of CharactersCount value

package-lock.json, packages/components/text-link/package.json, packages/components/text-link/src/TextLink.tsx
**TASK**: #1482 
Polymorphic behaviour is necessary if the user needs to turn a link into an html `button`. Or is using a custom link like `next/link` to wrap a `TextLink`.
=> feat(text-link): added polymorphic behaviour to text link

packages/components/tabs/src/TabsTrigger.styles.ts, packages/components/tag/src/Tag.styles.tsx
**TASK**: #1423 
- All components must have a background transparent in outline versions
- Tabs have a background transparent too
=> feat: outline design components must have transparent background

packages/components/checkbox/src/Checkbox.tsx
**TASK**: #1489
Since this was not set element could be appear in any parent whose position not static and so could mess up with the layout.
Setting the main div's position to `relative` makes sure it doesn't get rendered in a random div (ie: the first parent whose position is set).
=> fix(checkbox): set parent element's position to relative

package-lock.json, packages/components/text-link/package.json, packages/components/text-link/src/TextLink.doc.mdx, packages/components/text-link/src/TextLink.stories.tsx, packages/components/text-link/src/TextLink.tsx
**TASK**: #1485 
`TextLink` was bold by default. This is no longer wanted in the specs, font-weight should be inherited by default.
It's possible to have a bold `TextLink` in a `regular` font paragraph too.
=> feat(text-link): textLink inherit current font weight by default

package-lock.json, packages/components/tag/src/Tag.styles.tsx
**TASK**: subtask of #1509
We are using an external boxShadow on outlined `tag` instead of a border.
It means two things:
- an overflow:hidden will crop the "border"
- it is not vertically aligned with other tags (22px height instead of 20px)
Before
After
Bug example:
=> fix(tag): replaced boxShadow by a border

packages/components/chip/src/Chip.stories.tsx, packages/components/chip/src/Chip.tsx
Add ref props type to Chip component to avoid Type error when passing reference prop from outside.
=> feat(chip): add ref type to prop

package-lock.json, packages/components/button/src/Button.styles.tsx
**TASK**: subtask of #1509 
Keyboard focus styles was removing the outline of the button. Switch to using `border` now for `outlined` buttons, so it is no longer impacted by the focus styles.
Before
https://github.com/adevinta/spark/assets/2033710/2e876552-279d-451d-a442-f9914a8b35e7
After
https://github.com/adevinta/spark/assets/2033710/f98c03b3-08da-4bba-9526-2581886c957f
=> fix(button): fixed keyboard focus on outlined buttons

package-lock.json, packages/components/button/src/Button.doc.mdx, packages/components/button/src/Button.stories.tsx, packages/components/icon-button/src/IconButton.doc.mdx, packages/components/icon-button/src/IconButton.stories.tsx
I worked on multiple ways to approach toggle buttons, noticed a few things:
1. We will not have specific design specs for every intent/design for toggle buttons (`Button` and `IconButton`). 
2. Because we don't have any design, we can't make use of `defaultPressed` to apply any style that would make it obvious to the user that a button is pressed.
3. We are left with only `pressed` and `onPressedChange`. Pressed is just an alias for `aria-pressed`. `onPressedChange` is simply called on `onClick` internally to toggle the boolean.
4. `Toggle` from radix is not meant to be used as an HoC, it's a proper/distinct component. We are not meant to customize it into an HoC.
I came to the conclusion that we shouldn't do anything to manage toggle buttons, we already have what's necessary to manage …
=> feat(button): PROPOSAL - toggle button example

package-lock.json, packages/components/input/src/InputLeadingIcon.tsx, packages/components/input/src/InputTrailingIcon.tsx
Fixed #1547 
Because leading/trailing icons are technically outside of the input (just positionned over it) they were inheriting the font-size of the closest parent of the input, which was causing inconsistencies in icon sizes.
=> fix(input): leading and trailing icon font size

packages/utils/theme/src/defaultTheme.ts, packages/utils/theme/src/defaultThemeDark.ts
**TASK**: #1564
We noticed some differences between Spark theme implementation and Design specifications, particularly on the `onBackground` token.
After checking on [Figma](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?node-id=9056%3A7188&mode=dev) and [Spark Tokens Repository](https://github.com/adevinta/spark-tokens/blob/bdad6a8e2f248489d103516c62a72c7f83f8424d/tokens/spark/color/figmaTokens.json), we want to do some small updates to fix that.
=> fix(theme-utils): fix theme token values

packages/components/popover/src/PopoverAnchor.tsx, packages/components/popover/src/PopoverArrow.tsx, packages/components/popover/src/PopoverHeader.tsx
**TASK**: #1608 
Using `forwardRef` without exploiting the `ref` argument throws a react warning in the console/terminal.
Issue had been fixed partially on https://github.com/adevinta/spark/pull/1277.
=> fix(popover): fix ref warning when forward ref without using it

package-lock.json, packages/components/popover/src/PopoverContent.styles.ts
**TASK**: #1611 
Popover was cropped on screen smaller than 384px.
=> fix(popover): adapt popover width on smaller screens

packages/components/icons/scripts/build.mjs
This pull request resolves a potential performance concern by eliminating a nested regular expression in the main function, which is responsible for building icons. The previous regular expression pattern used for matching files, which was passed as an argument, was overly complex, especially considering our flat architecture for icons. This modification simplifies the pattern and removes the argument, making it more straightforward and less susceptible to unexpected behaviors.
- [x ] 🛠️ Tool
=> chore(icons): remove nested regex argument

package-lock.json, packages/components/dialog/src/DialogContent.styles.tsx, packages/components/dialog/src/DialogContent.tsx
**TASK**: #1620 
Check attached ticket please.
Summary: A piece of JSX around `Dialog.Content` does not have access to the radix context of the dialog and is always rendered as an invisible overlay in some cases. It prevents users from interacting with the page.
=> fix(dialog): dialog prevent mouse events in controlled mode

packages/components/dialog/src/DialogOverlay.tsx
**TASK**: #1631
Instead of not rendering `Dialog.Overlay` in fullscreen mode, we hide it with css.
Its presence is necessary because it freeze the scroll of the page in the background.
=> fix(dialog): render overlay also in fullscreen to freeze scroll on body

.github/workflows/mirror.yml
Vulcan only tracks internal gh repositories (gh enterprise) for now. The idea of this task+PR is to mirror the repo and at the same time add a periodic sync task in order to do never maintain its sync process manually.
This process will run:
["At minute 0 past hour 7 and 19 on Monday, Tuesday, Wednesday, Thursday, and Friday."](https://crontab.guru/#0_7,19_*_*_1,2,3,4,5)
When vulcan will be able to track public repositories the [mirror repo](https://github.dev.mpi-internal.com/scmspain/frontend-common--uilib-spark) will be removed and also this action.
This action is also prepared to be fired manually in order to sync it on demand if necessary
=> ci: mirror

package-lock.json, packages/components/drawer/package.json, packages/components/drawer/src/Drawer.stories.tsx, packages/components/drawer/src/DrawerBody.tsx, packages/components/drawer/src/DrawerCloseButton.tsx, packages/components/drawer/src/DrawerContent.styles.tsx
**TASK**: #1580 
[Drawer specs](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=11237%3A18026&mode=design&t=9LfSLg8myIUu2ngo-1)
- Updated close button positionning
- Adjusted `Drawer.Body` vertical padding
- Added `fullscreen` mode
- Adjusted `sm, md, lg` sizes
=> feat(drawer): final spec sync

packages/components/slider/src/Slider.test.tsx, packages/components/slider/src/SliderThumb.styles.ts, packages/components/slider/src/SliderThumb.tsx
**TASK**: #1471 
Due to Radix Slider specific implementation (that uses `.focus()`) we didn't have a perfect management of focus/focus-visible styles. Through this small PR we want to fix that, by adapting our styles during interaction, based on event types.
=> fix(slider): focus and focus-styles management

packages/components/rating/src/Rating.stories.tsx, packages/components/rating/src/Rating.test.tsx, packages/components/rating/src/Rating.tsx
**TASK**: #1577 
As user can't go back to zero when updating `Rating` component's value through mouse/pointer interactions, we want the same behaviour for keyboard.
=> feat(rating): prevent null value on keyboard interaction

package-lock.json, packages/components/dropdown/.npmignore, packages/components/dropdown/LICENSE.md, packages/components/dropdown/README.md, packages/components/dropdown/package.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/Dropdown.test.tsx, packages/components/dropdown/src/Dropdown.tsx, packages/components/dropdown/src/index.ts, packages/components/dropdown/tsconfig.json, packages/components/dropdown/vite.config.ts
Simply bootstraping `Dropdown` package in order to have smaller PRs when we start working on it. We will need it to work on it in parallel of working on `Select`.
=> feat(dropdown): dropdown bootstrap package

package-lock.json, packages/components/alert-dialog/src/AlertDialog.doc.mdx, packages/components/alert-dialog/src/AlertDialog.stories.tsx, packages/components/alert-dialog/src/AlertDialogContent.tsx, packages/components/dialog/src/Dialog.doc.mdx, packages/components/dialog/src/Dialog.stories.tsx, packages/components/dialog/src/DialogContent.styles.tsx, packages/components/dialog/src/DialogContent.tsx
**TASK**:  #1616 
This PR align `AlertDialog` with the specs.
- Remove `size` prop support. It should be fixed to `md` and the width should be adapted to the content.
- Add `isNarrow` prop to `Dialog` component
- Update both `Dialog` and `AlertDialog` documentation
=> 1616 component alertdialog review

packages/components/dialog/src/Dialog.doc.mdx, packages/components/dialog/src/Dialog.stories.tsx, packages/components/dialog/src/Dialog.test.tsx, packages/components/dialog/src/DialogBody.styles.ts, packages/components/dialog/src/DialogBody.tsx
**TASK**: #1652
Add `inset` prop to remove internal padding of `Dialog.Body` for better handling of full-width content
=> feat(dialog): add inset prop

packages/components/popover/src/Popover.doc.mdx, packages/components/popover/src/Popover.stories.tsx, packages/components/popover/src/Popover.test.tsx, packages/components/popover/src/PopoverContent.styles.ts, packages/components/popover/src/PopoverContent.tsx
**TASK**: #1653 
There is a common use case in Polaris where users want to have elements within the Popover component that takes up the full width.
Currently, achieving this requires overriding the internal padding of the component. To prop would make this use case easier and more intuitive.
When set to true, this prop will remove the internal padding of the component, allowing for a full-width image or content.
=> feat(popover): add inset prop to popover

packages/components/drawer/src/Drawer.doc.mdx, packages/components/drawer/src/Drawer.stories.tsx, packages/components/drawer/src/Drawer.test.tsx, packages/components/drawer/src/DrawerBody.styles.ts, packages/components/drawer/src/DrawerBody.tsx
**TASK**: #1654 
There is a common use case in Polaris where users want to have elements within the Drawer component that takes up the full width.
Currently, achieving this requires overriding the internal padding of the component. To prop would make this use case easier and more intuitive.
When set to true, this prop will remove the internal padding of the component, allowing for a full-width image or content.
=> feat(drawer): add inset prop to drawer

packages/components/input/src/Input.stories.tsx, packages/components/input/src/InputGroup.tsx
**TASK**: #1666 
Internal state was derivated from prop instead of FormField context.
=> fix(input): derivate input state from formField when possible

package-lock.json, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownItem.tsx, packages/components/dropdown/src/DropdownItemText.tsx, packages/components/dropdown/src/index.ts, packages/components/dropdown/src/utils.ts
**TASK**: #1670 
`downshift` need each item to have a raw string as a label for autocompletion/highlighting of items.
If `children` is a string
```
<Dropdown.Item value="book-9">Anna Karenina</Dropdown.Item>
```
=> Then downshift will use `children` as a value for autocompletion/highlighting.
But if `children` is custom markup, for example:
```
<Dropdown.Item value="book-10" className="gap-md">
<Dropdown.ItemText>Crime and Punishment</Dropdown.ItemText>
<Tag>New</Tag>
</Dropdown.Item>
```
=> Then we use `Dropdown.ItemText` to tell `downshift` "This is where the raw text value that you need is located".
=> feat(dropdown): enable custom jsx in DropdownItem

package-lock.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/Dropdown.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/utils.ts
**TASK**: #1684 
Controlled mode is provided for two features:
- `value` management using `value, onValueChange, defaultValue` to stick with other Spark components API
- `open` management using `open, onOpenChange, defaultOpen` to stick with other Spark components API
=> 1684 components dropdown controlled mode

package-lock.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/Dropdown.test.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownItem.tsx, packages/components/dropdown/src/DropdownItemContext.tsx, packages/components/dropdown/src/DropdownItemText.tsx, packages/components/dropdown/src/DropdownTrigger.tsx, packages/components/dropdown/src/DropdownValue.tsx, packages/components/dropdown/src/types.ts, packages/components/popover/src/PopoverContent.styles.ts
**TASK**: 1687
- First step of multiple selection mode.
- ⚠️ does not yet allow controlled mode in multiple selection (future PR)
- ⚠️ `Dropdown.Value` does not reflect multiple selection values yet (future PR)
=> feat(dropdown): multiple selection dropdown

package-lock.json, packages/components/checkbox/src/CheckboxIndicator.tsx, packages/components/checkbox/src/CheckboxInput.styles.ts
**TASK**: #1728 
`text-surface` was applied to the checked checkboxes icons for every intent.
Instead it should have been the `text-on-[INTENT]` for each intent. Otherwise contrast is not consistant on all themes.
=> fix(checkbox): apply proper color on checkbox ticks per intent

package-lock.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/Dropdown.test.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownItemContext.tsx, packages/components/dropdown/src/DropdownTrigger.tsx, packages/components/dropdown/src/utils.ts
**TASK**: #1687 
Controlled mode is now managing array of strings for `multiple` selection mode.
- `value`, `onValueChange` and `defaultValue` now accepts array of strings.
- `multiple` prop helps TS infer that those prop have the correct type for the user
- added descriptions to most stories
=> Controlled multiple selection

package-lock.json, packages/components/dropdown/src/DropdownPopover.tsx
**TASK**: #1740 
Enabled popover props to work on the dropdown popover.
=> feat(dropdown): enabled passing props to dropdown popover

package-lock.json, package.json
The v1.9.1 of the @adevinta/tailwind-config-viewer will filter out the `bg-on-*` values from the background category.
=> feat: bump TCV to 1.9.1

packages/components/switch/src/SwitchInput.styles.ts, packages/components/switch/src/SwitchInput.tsx
To discuss. Some teams using our Switch component reported that it's toggle animation was lagging when clicking on it trigger heavy computation of their pages.
Heavy computation is an issue on their side, but it seems those styles help makes seems smoother (we tested it).
WDYT ?
=> fix(switch): improved animation performance

packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/Dropdown.test.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownItem.tsx, packages/components/dropdown/src/DropdownItems.tsx, packages/components/dropdown/src/DropdownStateIndicator.tsx, packages/components/dropdown/src/DropdownTrigger.tsx
**TASK**: #1752 
Implementing states for dropdown trigger:
- error, alert and success states.
- a state indicator is displayed (icon) for colorblind people who can't see the outline color.
- Focus styles have been updated to match the Figma specs
=> feat(dropdown): dropdown states

package-lock.json, packages/components/dropdown/src/DropdownItems.tsx, packages/components/dropdown/src/DropdownPopover.tsx, packages/components/dropdown/src/DropdownTrigger.tsx, packages/components/popover/src/Popover.doc.mdx, packages/components/popover/src/PopoverContent.styles.ts
**TASK**: #1771 
Dynamic height resizing on Popover.
It allows `Dropdown.Popover` to optimize height dynamically and display as many items as possible.
https://github.com/adevinta/spark/assets/2033710/50491560-d2b8-4e86-b847-833ed44ad920
=> feat(popover): dynamic height management

package-lock.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/DropdownDivider.tsx, packages/components/dropdown/src/DropdownGroup.tsx, packages/components/dropdown/src/DropdownItem.tsx, packages/components/dropdown/src/DropdownItemIndicator.tsx, packages/components/dropdown/src/DropdownItemText.tsx, packages/components/dropdown/src/DropdownItems.tsx, packages/components/dropdown/src/DropdownLabel.tsx, packages/components/dropdown/src/DropdownLeadingIcon.tsx, packages/components/dropdown/src/DropdownPopover.tsx, packages/components/dropdown/src/DropdownTrigger.tsx, packages/components/dropdown/src/DropdownValue.tsx, packages/components/dropdown/src/utils.ts
=> docs(dropdown): FWD ref and component-names

packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownTrigger.styles.tsx, packages/components/dropdown/src/DropdownTrigger.tsx
Closes #1686 
- disabled mode
- disabled mode (inherited from FormField wrapper)
- readOnly mode
- readOnly mod (inherited from FormField wrapper)
- added stories
=> feat(dropdown): disabled and readOnly modes

package-lock.json, packages/components/dropdown/src/Dropdown.test.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/useDropdown.ts
=> refactor(dropdown): removed downshift logic from context logic

package-lock.json, packages/components/select/src/Select.doc.mdx, packages/components/select/src/Select.stories.tsx, packages/components/select/src/Select.test.tsx, packages/components/select/src/Select.tsx, packages/components/select/src/SelectContext.tsx, packages/components/select/src/SelectGroup.tsx, packages/components/select/src/SelectItem.tsx, packages/components/select/src/SelectItems.tsx, packages/components/select/src/SelectItemsGroup.tsx, packages/components/select/src/SelectItemsGroupContext.tsx, packages/components/select/src/SelectLabel.tsx, packages/components/select/src/SelectLeadingIcon.tsx, packages/components/select/src/SelectStateIndicator.tsx, packages/components/select/src/SelectTrigger.styles.tsx, packages/components/select/src/SelectTrigger.tsx, packages/components/select/src/SelectValue.tsx, packages/components/select/src/index.ts, packages/components/select/src/types.ts, packages/components/select/src/utils.ts
**TASK**: #1793 
Most of the work that has been approved for the dropdown is merged into Select in the PR.
The code had to be adapted to match the HTML select API.
=> feat(select): merge dropdown logic into select

package-lock.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/Dropdown.test.tsx, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownItem.tsx, packages/components/dropdown/src/DropdownItems.tsx, packages/components/dropdown/src/DropdownPopover.tsx, packages/components/dropdown/src/DropdownTrigger.tsx, packages/components/dropdown/src/useDropdown.ts, packages/components/dropdown/src/utils.ts, packages/components/popover/src/PopoverContent.styles.ts, packages/components/select/src/Select.doc.mdx
1. fixed bug related to z-index inside popover. Downshift refs should always be merged with our forwarded refs.
2. fixed bug related to focus forwarding. When Dropdown was used inside a Dialog, it was breaking `onOpenAutoFocus` behaviour.
=> fix(dropdown): z-index and focus behaviour issues

package-lock.json, packages/components/popover/src/PopoverContent.styles.ts
Removing `relative` class on `Popover.Content` as it breaks `Popover.Arrow` positionning.
=> fix(popover): broken popover arrow caused by relative positionning

packages/components/dropdown/package.json, packages/components/dropdown/src/DropdownValue.tsx, packages/components/select/package.json, packages/components/select/src/SelectContext.tsx, packages/components/select/src/SelectValue.tsx
Missing deps in `@spark-ui/select` was causing context issue with `form-field
`
=> fix(select): fix select deps

packages/components/drawer/src/DrawerContent.styles.tsx
**TASK**: #1840 
On Android and iOS, Drawer had some issues due to `vh` usage. So we replace it with classic top/bottom positionning.
**BEFORE/AFTER:**
=> fix(drawer): fix vh issue on drawer

package-lock.json, packages/components/dropdown/src/DropdownItemIndicator.tsx
**TASK**: #1844 
During testing session, we found out that ItemIndicator icon was invisible on safari only.
We forgot to wrap the Check icon with `@spark-ui/icon`. I don't know why it was only broken on Safari, but it fixes the bug.
=> fix(dropdown): fixed missing ItemIndicator on Safari

package-lock.json, packages/components/drawer/src/Drawer.doc.mdx, packages/components/drawer/src/Drawer.stories.tsx, packages/components/drawer/src/DrawerContent.styles.tsx
**TASK**: #1829 
Design team asked for fluid size on Drawer.
=> feat(drawer): add fluid size

packages/components/badge/src/Badge.stories.tsx, packages/components/badge/src/BadgeItem.styles.tsx, packages/components/badge/src/BadgeItem.tsx, packages/components/badge/src/config.ts
**TASK**: #1764 
We want to fix empty badge (no count) size, as specified in Figma file.
=> fix(badge): fix badge size on empty content

packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/DropdownItems.tsx
**TASK**: #1838 
Please check this issue https://github.com/radix-ui/primitives/issues/1159
For now the best I can do is prevent Radix from setting `pointerEvents: "none"` in the style `attributes` of `Dropdown.Items` (which is merged with `Popover.Content` through `asChild`)
=> fix(dropdown): prevent radix focus trap to disable scroll inside dropdown

.storybook/preview-head.html, .storybook/preview.jsx
This PR ensures a banner is displayed on all components marked as experimental. This banner warns users to proceed with caution when using these components.
-->
=> docs: add experimental banner

package-lock.json, packages/components/dropdown/package.json, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/select/package.json, packages/components/select/src/Select.stories.tsx
- Releasing `@spark-ui/dropdown` as stable
- Releasing `@spark-ui/select` as stable
=> fix(dropdown): release dropdown and select as stable

packages/components/combobox/src/Combobox.doc.mdx, packages/components/combobox/src/Combobox.stories.tsx, packages/components/combobox/src/ComboboxDisclosure.tsx, packages/components/combobox/src/ComboboxTrigger.tsx, packages/components/combobox/src/index.ts, packages/components/combobox/src/tests/Combobox.test.tsx, packages/components/combobox/src/tests/singleSelection.test.tsx
**TASK**: #1885
Add optional `Combobox.Disclosure` button to show users that a list is attached to the input and can be opened.
=> feat(combobox): combobox disclosure button

package-lock.json, packages/components/snackbar/package.json, packages/components/snackbar/src/SnackBarItemContext.tsx, packages/components/snackbar/src/Snackbar.doc.mdx, packages/components/snackbar/src/Snackbar.stories.tsx, packages/components/snackbar/src/Snackbar.test.tsx, packages/components/snackbar/src/Snackbar.tsx, packages/components/snackbar/src/SnackbarItem.tsx, packages/components/snackbar/src/index.ts
**TASK**: #1893 
In this new PR we want to setup base logic of the Snackbar incoming component. It will be implemented by adding a `<SnackBar />` within the codebase, and then controlling snackbar queue with dedicated methods (such as `addSnackBar`).
=> feat(snackbar): init snackbar data flow logic

package-lock.json, packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/useDropdown.ts
It was impossible to select an item with value `""` (empty string) in controlled mode inside `Dropdown`.
The reason is an empty string is considered `falsy`. By checking `!= null` instead we only exclude items whose value is `null` or `undefined`.
=> fix(dropdown): fixing empty value items selection

package-lock.json, package.json, packages/components/combobox/package.json, packages/components/dropdown/package.json
Downshift `8.3.2` introduced a focus issue where the last dropdown on the page gets focus on first rerender.
It has been fixed today with `8.3.3`: https://github.com/downshift-js/downshift/pull/1575
=> fix(dropdown): fix autofocus of dropdown following downshift update

packages/components/snackbar/src/Snackbar.test.tsx, packages/components/snackbar/src/Snackbar.tsx, packages/components/snackbar/src/useSnackbarGlobalStore.ts
**TASK**: #1893 
To avoid duplicate markup that could bring some W3C and/or a11y issues we want to ensure that one application will only have one snackbar container, thanks to `useSyncExternalStore` React hook.
=> feat(snackbar): use external store to ensure single snackbar container

packages/components/dialog/src/Dialog.tsx
**TASK**: #1930
When the Dialog is closed, ensure that the focus is restored to the element that was previously active when the Dialog was opened.
=> feat(dialog): implement focus capture and restoration in dialog component

package-lock.json, package.json, packages/components/combobox/package.json, packages/components/combobox/src/Combobox.doc.mdx, packages/components/combobox/src/Combobox.stories.tsx, packages/components/combobox/src/ComboboxClearButton.tsx, packages/components/combobox/src/ComboboxContext.tsx, packages/components/combobox/src/ComboboxDisclosure.tsx, packages/components/combobox/src/ComboboxInput.tsx, packages/components/combobox/src/ComboboxLeadingIcon.tsx, packages/components/combobox/src/ComboboxSelectedItems.tsx, packages/components/combobox/src/ComboboxTrigger.styles.tsx, packages/components/combobox/src/ComboboxTrigger.tsx, packages/components/combobox/src/tests/multipleSelection.test.tsx, packages/components/combobox/src/tests/test-utils.ts, packages/components/combobox/src/useCombobox/multipleSelectionReducer.ts, packages/components/combobox/src/utils/index.ts, packages/components/combobox/src/utils/useWidthIncreaseCallback.ts, vitest.setup.ts
**TASK**: #1887 
`nowrap` (single line) behaviour for multiple selection.
Sometimes a combobox height should be restricted to 1 line (44px). The selected items chips in multiple selection expends the height by default.
If you need the combobox aligned with other component (Input, Button, etc) OR if you are using it in a sticky navigation, it might be useful to restrict it to 1 line only.
When this behaviour is enabled, resizing the component or selecting items in the menu will scroll the typing area into view.
Default wrap behaviour:
Single line (no wrap) behaviour:
=> feat(combobox): nowrap behaviour for multiselect

package-lock.json, packages/components/combobox/src/Combobox.doc.mdx, packages/components/combobox/src/Combobox.stories.tsx, packages/components/combobox/src/ComboboxContext.tsx
**TASK**: #1963 
- `open` and `onOpenChange` props to control the open state of the combobox from outside.
=> feat(combobox): controlled combobox open state

package-lock.json, packages/components/combobox/package.json, packages/components/combobox/src/Combobox.doc.mdx, packages/components/combobox/src/Combobox.stories.tsx, packages/components/combobox/src/ComboboxContext.tsx, packages/components/combobox/src/ComboboxItems.tsx
**TASK**: 
Use the `isLoading` prop to render the combobox in loading state. This will prepend a spinner inside the combobox.
=> feat(combobox): isLoading + SearchModal example

packages/components/combobox/src/Combobox.stories.tsx
The "non case-sensitive" story was actually doing a case-sensitive check (not matching the description)
=> docs(combobox): fixed custom filtering story

packages/components/dialog/src/DialogContext.tsx
Use optional chaining operator to safely access node id, preventing runtime errors when `node.type` is not present
=> fix(dialog): use optional chaining operator to safely access node id

package-lock.json, packages/components/dropdown/src/Dropdown.doc.mdx, packages/components/dropdown/src/DropdownPopover.tsx, packages/components/dropdown/src/DropdownPortal.tsx, packages/components/dropdown/src/index.ts
We portalled `Dropdown.Popover` to fix a bug, but it introduced another bug: Dropdowns are now rendered portalled like `Dialog` so they share the same stacking context.
This is bad because their z-index are:
```
dropdown: '1000',
modal: '1400',
```
So now, a Dropdown inside a dialog is visually hidden behind it.
Instead of hard-coding the wrapping of `Dropdown.Popover` with a `Portal`, I added `Dropown.Portal` as part of the compound to make it optional. That way by default a dropdown is not portalled and inherits the closest stacking context.
A dropdown inside a dialog has a z-index of `1000` INSIDE a stacking context of `1400`.
=> fix(dropdown): z-index conflict between dialog and dropdown

packages/components/textarea/src/Textarea.doc.mdx, packages/components/textarea/src/Textarea.stories.tsx
**TASK**: #2016 
While working on this ticket we realized the complexity that could arise from considering changes in the text area's font size and so forth. It's wise to take a step back and not go any further.
To address the issue of the unappealing scrollbar, we recommend that our consumers use the `scrollbar-color` CSS property to customize scrollbar styles instead. This PR just adds a story showcasing a customised scrollbar
=> feat(textarea): add story showcasing customised scrollbar

packages/components/checkbox/src/Checkbox.doc.mdx, packages/components/checkbox/src/Checkbox.stories.tsx, packages/components/checkbox/src/Checkbox.test.tsx, packages/components/checkbox/src/Checkbox.tsx, packages/components/checkbox/src/CheckboxGroup.tsx, packages/components/checkbox/src/CheckboxGroupContext.tsx, packages/components/radio-group/src/Radio.tsx, packages/components/radio-group/src/RadioGroup.doc.mdx, packages/components/radio-group/src/RadioGroup.stories.tsx, packages/components/radio-group/src/RadioGroup.test.tsx, packages/components/radio-group/src/RadioGroup.tsx, packages/components/radio-group/src/RadioGroupContext.tsx, packages/components/radio-group/src/RadioGroupProvider.tsx, packages/components/switch/src/Switch.doc.mdx, packages/components/switch/src/Switch.stories.tsx, packages/components/switch/src/Switch.test.tsx, packages/components/switch/src/Switch.tsx, packages/components/switch/src/SwitchInput.tsx
Our **Switch**, **Checkbox**, and **RadioGroup** components currently have their labels placed on the right side of the input. This PR introduce a `reverse` prop that, when enabled, will place the label on the left side of the input.
This PR will also address #2005
=> feat: add "reverse" prop to have label placed on the left side of the input

package-lock.json, package.json, packages/components/combobox/package.json, packages/components/combobox/src/tests/singleSelection.test.tsx, packages/components/dropdown/package.json
Bump Downshift major update (we go from `8.3.3` to `9.0.4`)
We are lucky the breaking changes only concerns part of the hooks that we were not using, see changes: https://github.com/downshift-js/downshift/compare/v8.5.0...v9.0.0#diff-66d20b65c108edd6f401d263d1b6a09742f216177685ebacdee161e0134872a4R1
This is why I don't flag this as a breaking change on our side.
=> chore(dropdown): downshift 9

packages/components/dropdown/src/Dropdown.stories.tsx, packages/components/dropdown/src/DropdownItems.tsx
This PR addresses a bug:
Which cannot be reproduced when running Storybook locally, in scenarios such as when a Dropdown is nested within a Dialog, the "props" object, containing styles computed by Radix may erroneously contain "pointerEvents = 'none'", while the Dropdown is open, making it impossible to select a value using a pointer device
=> fix(combobox): address pointerEvents related bug

package-lock.json, packages/components/snackbar/src/Snackbar.doc.mdx
It seemed that initial documentation wasn't clear enough, so we try here to improve it.
=> docs(snackbar): improve docs to make it clearer

package-lock.json, packages/components/checkbox/package.json, packages/components/checkbox/src/Checkbox.tsx, packages/components/combobox/package.json, packages/components/combobox/src/ComboboxContext.tsx, packages/components/combobox/src/ComboboxItemText.tsx, packages/components/combobox/src/ComboboxItemsGroupContext.tsx, packages/components/dropdown/package.json, packages/components/dropdown/src/DropdownContext.tsx, packages/components/dropdown/src/DropdownItemText.tsx, packages/components/dropdown/src/DropdownItemsGroupContext.tsx, packages/components/form-field/package.json, packages/components/form-field/src/FormField.tsx, packages/components/form-field/src/FormFieldContext.tsx, packages/components/form-field/src/FormFieldMessage.tsx, packages/components/form-field/src/FormFieldProvider.tsx, packages/components/popover/package.json, packages/components/popover/src/PopoverContext.tsx, packages/components/popover/src/PopoverHeader.tsx, packages/components/progress-tracker/src/ProgressTrackerContext.ts, packages/components/progress-tracker/src/ProgressTrackerStep.tsx, packages/components/progress/package.json, packages/components/progress/src/ProgressContext.tsx, packages/components/progress/src/ProgressLabel.tsx, packages/components/radio-group/package.json, packages/components/radio-group/src/Radio.tsx, packages/components/select/src/SelectContext.tsx, packages/components/switch/package.json, packages/components/switch/src/Switch.tsx
**TASK**: #2049 
To avoid duplicate ID issues with compound pattern, we want to prefix our generated IDs, and also to use React `useId` instead of Radix custom implementation, which doesn't seem to be relevant to our usage.
=> refactor: deprecate radix useId for react one

packages/components/select/src/Select.test.tsx, packages/components/select/src/SelectContext.tsx
**TASK**: #2062 
While using the `Select` component in controlled mode, two issues have been observed:
1. The `onValueChange` prop is executed on initial render, even though the value has not been changed.
2. Each time the value changes, the `onValueChange` prop is executed twice.
Repro ➡ https://stackblitz.com/edit/stackblitz-starters-ulfsq2?file=pagesContent%2Findex.tsx
The problem seems to originate from `packages/components/select/src/SelectContext.tsx`, specifically this piece of code:
```tsx
useEffect(() => {
if (valueProp) setValue(valueProp)
}, [valueProp, setValue])
```
The weird thing is, when we comment out what's inside the `useEffect`, all the tests still pass. And even when we interact with the component in the browser (in both controlled and uncontrolled modes), it doesn't …
=> fix(select): remove code causing excessive calls to the onValueChange prop

packages/components/select/src/Select.test.tsx, packages/components/select/src/SelectItems.tsx
Associate `label` and `select` elements, so that when a user clicks on the label associated with a `Select`, the `Select` will receive focus.
=> feat(select): associate label and select elements

package-lock.json, packages/components/combobox/src/ComboboxContext.tsx, packages/components/combobox/src/ComboboxItem.tsx, packages/components/combobox/src/useCombobox/multipleSelectionReducer.ts
- Selecting an item in multiple selection, then typing to filter it out, then pressing Enter, was selecting the hidden item instead of reseting highlightedIndex to -1 (start of the list)
=> fix(combobox): fix combobox highlighted index while typing

package-lock.json, packages/components/combobox/src/ComboboxInput.tsx, packages/components/combobox/src/ComboboxTrigger.tsx
It has been reported that on smaller screens, the clear button and/or disclosure button were overflowing the Combobox to the right side.
BEFORE
AFTER
=> fix(combobox): combobox content overflow on smaller screens

packages/components/combobox/src/ComboboxEmpty.tsx
Padding was missing in `Combobox.Empty` (to match combobox item padding)
=> fix(combobox): missing padding in combobox empty view

packages/components/combobox/src/ComboboxInput.tsx
See https://github.com/downshift-js/downshift/issues/1108#issuecomment-674180157
=> fix(combobox): preserve combobox cursor position upon change

packages/components/combobox/src/useCombobox/singleSelectionReducer.ts
Pressing escape once closes the combobox menu.
Pressing it once more clears the input.
When clearing the input, it is important we also clear the internal state of the input value (if not, focusing back in the input later will restore its value to that of the internal state)
=> fix(combobox): clear internal input value on escape

package-lock.json, packages/components/combobox/src/Combobox.doc.mdx, packages/components/combobox/src/Combobox.stories.tsx
- fixed "Combo Box" typo in doc.
- removed `allowCustomValue` prop from stories where it was unnecessary.
=> docs(combobox): fixed typos and invalid props in combobox stories

package-lock.json, packages/components/combobox/src/ComboboxSelectedItems.tsx
**TASK**: #2142 
Focus styles for selected items were missing, resulting in different outline styles depending on the browser.
https://github.com/adevinta/spark/assets/2033710/041eb132-140e-416b-b389-b52502d37689
=> fix(combobox): apply focus styled to combobox selected items

package-lock.json, packages/components/link-box/src/LinkBox.doc.mdx, packages/components/link-box/src/LinkBox.stories.tsx, packages/components/link-box/src/LinkBox.test.tsx, packages/components/link-box/src/LinkBox.tsx, packages/components/link-box/src/LinkBoxLink.tsx, packages/components/link-box/src/LinkBoxRaised.tsx, packages/components/link-box/src/index.ts
**TASK**: #2132 
We were not sure about using css selectors to raise nested links/elements on top of the overlay. Instead we introduce `LinkBox.Raised` to explicitely flag which components should remain on top.
=> feat(link-box): added Linkbox.Link to raised components inside the box

packages/components/snackbar/src/Snackbar.doc.mdx, packages/components/snackbar/src/Snackbar.stories.tsx, packages/components/snackbar/src/Snackbar.test.tsx, packages/components/snackbar/src/SnackbarItem.styles.ts, packages/components/snackbar/src/SnackbarItem.tsx, packages/components/snackbar/src/SnackbarItemAction.tsx, packages/components/snackbar/src/SnackbarItemClose.tsx, packages/components/snackbar/src/SnackbarItemIcon.tsx
**TASK**: #2147 
Following design specs update, we want to improve item layout following way:
For more infos: https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=43448-28117&t=7KNS8UY1D2Fu3ifo-4
=> feat(snackbar): add option to force action btn display on new line

package-lock.json, packages/components/link-box/src/LinkBox.doc.mdx
I forgot to add the `LinkBox` compound `ArgTypes` (props table)
=> docs(link-box): added props tables to linkBox docs

packages/utils/internal-utils/package.json, packages/utils/internal-utils/vite.config.ts
Inside the `react-children-utilities` util package, we reference `React`, but we didn't declare it as a dependency in the `package.json`.
We also didn't include it in the rollup config, which could cause some version dependency mismatches at the call site
=> fix(internal-utils): update rollup config and include external peer dependencies to avoid potential dependency mismatches at the call site

package-lock.json, packages/components/combobox/src/Combobox.doc.mdx, packages/components/combobox/src/Combobox.stories.tsx, packages/components/combobox/src/ComboboxContext.tsx, packages/components/combobox/src/ComboboxInput.tsx, packages/components/combobox/src/ComboboxItem.tsx, packages/components/combobox/src/tests/multipleSelection.test.tsx, packages/components/combobox/src/tests/singleSelection.test.tsx
**TASK**: #2183 
1. Read attached issue.
2. Proposal is to replace `autoFilter` (boolean), by `filtering: "auto" | "none" | "strict"`
`strict` matches the previous default behaviour, `auto` is the new/improved way for filtering, where the filtering only applies once the user starts typing.
For example, if the user selects a value in the list, it will reset/cancel the filtering so they can explore the full list of values.
=> feat(combobox): improved UX of default combobox filtering behaviour

packages/components/checkbox/src/Checkbox.test.tsx, packages/components/checkbox/src/Checkbox.tsx
**TASK**:#2205
When a `CheckboxGroup` is marked as required, we should remove the required attribute from individual checkboxes as soon as one checkbox is checked.
=> fix(checkbox): remove the required attribute from individual checkboxes as soon as 1 checkbox is checked

package-lock.json, packages/components/select/src/SelectItems.tsx, packages/components/select/src/SelectTrigger.styles.tsx, packages/components/select/src/SelectValue.tsx
**TASK**: #2136 
On the `Select` component `disabled` and `readOnly` states seem to be desync with input styles. We want to harmonize and fix this.
=> fix(select): fix disabled and readonly styles

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, package-lock.json
**TASK**: #2210 
Issues created from issue templates are now attached to `Spark` project (backlog) with the `Needs Triage` label.
Note: I tried to make it assigned to the `Web` team automatically, but this is not possible for now: https://github.com/orgs/community/discussions/86679
=> It means every issue we receive must be manually assigned to `Web` to appear on the Web board. Let's hope GH improves this.
=> chore: auto assign gh issue templates to project

packages/components/combobox/src/ComboboxSelectedItems.tsx
Missing `key` attribute on `Combobox.SelectedItems` loop triggers a warning in the console.
=> fix(combobox): missing key attribute on selected items

package-lock.json, packages/components/accordion/src/Accordion.doc.mdx, packages/components/accordion/src/Accordion.stories.tsx, packages/components/accordion/src/Accordion.test.tsx, packages/components/accordion/src/Accordion.tsx, packages/components/accordion/src/AccordionItemHeader.tsx, packages/components/accordion/src/index.ts
Managing heading levels for `Accordion` items triggers. As per ARIA accordion pattern guidelines: 
```
Each accordion header button is wrapped in an element with role [heading](https://w3c.github.io/aria/#heading) that has a value set for [aria-level](https://w3c.github.io/aria/#aria-level) that is appropriate for the information architecture of the page.
```
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/
=> feat(accordion): accordion item header

packages/components/accordion/src/AccordionItemTrigger.tsx
Updating `ItemTrigger` base style to be flex, so that if an icon is used inside as the spec says, it will be an horizontal layout and vertically centered.
=> style(accordion): styles adjustement to match final specs

packages/components/icon/src/Icon.styles.tsx
**TASK**: #2233 
When icons are before/after a long text inside a flex container, they shrink (unwanted behaviour).
For example inside a `FormField` helper/error message, or inside an `Accordion` trigger.
=> fix(icon): fix icon shrinking inside flex containers

packages/components/dialog/package.json, packages/components/dialog/src/Dialog.test.tsx, packages/components/dialog/src/DialogCloseButton.tsx, packages/components/dialog/src/DialogContent.styles.tsx, packages/components/dialog/src/DialogContext.tsx, packages/components/dialog/src/DialogTitle.tsx
Adjust the handling of the hasCloseButton flag to avoid a potential infinite loop with React 19
=> fix(dialog): adjust the handling of the hasCloseButton flag to avoid a potential infinite loop with React 19

package-lock.json, packages/utils/cli/package.json, packages/utils/cli/src/scan/index.mjs, packages/utils/cli/src/scan/loadConfig.mjs
Initially we used `lodash.merge` to merge config customizations, but it prevented us to override options properly. It finally appears that this util was not relevant.
=> fix(cli-utils): fix config merge method to allow proper option override

packages/components/tag/src/Tag.stories.tsx, packages/components/tag/src/Tag.styles.tsx, packages/components/tag/src/Tag.tsx, packages/components/tag/src/variants/filled.ts
**TASK**: #2243
Add surface intent according to updated design specs
=> feat(tag): add "surface" intent

packages/components/tabs/src/Tabs.doc.mdx, packages/components/tabs/src/Tabs.stories.tsx, packages/components/tabs/src/Tabs.test.tsx, packages/components/tabs/src/Tabs.tsx, packages/components/tabs/src/TabsContent.styles.ts, packages/components/tabs/src/TabsContent.tsx, packages/components/tabs/src/TabsContext.tsx
**TASK**: #2283
see related issue #2283
=> feat(tabs): add forceMount prop to retain inactive tab content in the DOM

packages/components/accordion/src/AccordionItemContent.tsx
Resolve animation issues by moving padding to the first child of AccordionItemContent, preventing vertical layout shifts
**before:**
___
**after:**
=> fix(accordion): move padding to first element of AccordionItemContent to fix animation shifts

package-lock.json, packages/components/combobox/package.json, packages/components/combobox/src/tests/edgeCases.test.tsx
We recently encountered a situation where one of our users was unable to interact with our **Combobox** (with a pointer device) when it was placed inside a **Spark Dialog**.
After investigating, we discovered that the issue was with the **Spark Dialog**, not the Combobox itself.
To catch when similar bugs occur in the future, we are adding test cases to test our Combobox within a Spark Dialog as part of the Combobox tests.
=> test(combobox): add additional edge cases

package-lock.json, packages/components/combobox/src/ComboboxEmpty.tsx
`Combobox.Empty` styles were not aligned with Figma (font-size and text-color). https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=28629-4000&t=GO6qlR8llASgHV9h-1
Before
After
=> style(combobox): missing styles on Combobox.Empty

packages/components/tabs/src/Tabs.doc.mdx
Testing semantic commit bump with new fixed versioning strategy for package publishing (with Lerna).
=> docs(tabs): typo in tabs doc

config/component.ts, config/index.ts, packages/components/snackbar/vite.config.ts
For a reason I still don't completely understand, the **JSX runtime** was bundled in our `.js` files from our `dist` folder for the Snackbar component (since v1.1.9). This PR addresses that.
=> fix(snackbar): update vite config to exclude JSX runtime bundling

e2e/dropdown-within-dialog/index.spec.tsx, e2e/dropdown-within-dialog/index.tsx, e2e/main.tsx, package-lock.json, packages/components/combobox/src/ComboboxItems.tsx, packages/components/dropdown/src/DropdownItems.tsx, packages/components/popover/package.json
Bump `@radix-ui/react-popover` and fixes regression in Combobox.
Added e2e tests for similar use-case (combining Dialog with Dropdown)
=> fix(combobox): make combobox popover non clickable while closed

.storybook/manager.js, packages/components/icons/src/index.doc.mdx, packages/components/icons/src/index.stories.tsx
Spark icons list should not be publicly visible. The UI listing is only made available for internal purpose.
=> docs(icons): hide icons list from public documentation

package-lock.json, packages/components/breadcrumb/.npmignore, packages/components/breadcrumb/LICENSE.md, packages/components/breadcrumb/README.md, packages/components/breadcrumb/package.json, packages/components/breadcrumb/src/Breadcrumb.doc.mdx, packages/components/breadcrumb/src/Breadcrumb.stories.tsx, packages/components/breadcrumb/src/Breadcrumb.test.tsx, packages/components/breadcrumb/src/Breadcrumb.tsx, packages/components/breadcrumb/src/BreadcrumbCurrentPage.tsx, packages/components/breadcrumb/src/BreadcrumbItem.tsx, packages/components/breadcrumb/src/BreadcrumbLink.tsx, packages/components/breadcrumb/src/BreadcrumbSeparator.tsx, packages/components/breadcrumb/src/index.ts, packages/components/breadcrumb/tsconfig.json, packages/components/breadcrumb/vite.config.ts
**TASK**: #2366 
`Breadcrumb` component boilerplate and anatomy proposal. Inspired by https://ui.shadcn.com/docs/components/breadcrumb
=> feat(breadcrumb): new breadcrumb component

package-lock.json, packages/components/accordion/package.json, packages/components/collapsible/package.json
Bump `@zagjs` packages to latest 0.67.0 version, but use a fixed version instead of a caret one, according to our [agreement](https://github.com/adevinta/spark/wiki/Agreements#managing-dependencies-within-spark-components)
=> chore: bump @zag-js packages to fixed version 0.67.0

packages/components/pagination/vite.config.ts
For a reason I still don't completely understand, the **JSX runtime** was bundled in our `.js` files from our `dist` folder for the Pagination component. This PR addresses that.
See also ➡️ #2315
=> fix(pagination): update vite config to exclude JSX runtime bundling

packages/components/form-field/src/FormFieldLabel.tsx, packages/components/form-field/src/FormFieldRequiredIndicator.tsx
**TASK**: [SPA-6](https://jira.ets.mpi-internal.com/browse/SPA-6)
- Update `FormField.Label` to not be a `flex` container, in order to inline the `RequiredIndicator` with the label text.
=> style(form-field): inline required indicator placement

packages/components/dialog/src/DialogContent.tsx, packages/components/drawer/src/DrawerContent.tsx
**TASK**: [SPA-193](https://jira.ets.mpi-internal.com/browse/SPA-193)
Dialog/Drawer have a focus trap by default. It applies `pointer-events-none` on the whole page in the background to disabled clicks.
But some components might be displayed on top of dialogs and have a stronger `z-index` (ex: `Snackbar`, `Popover`). Such components must remain interactive, so they have `pointer-events-auto` on them.
Let's say I am inside a dialog:
1. I click somewhere inside the dialog that triggers a snackbar.
2. I click the close button of the snackbar displayed.
3. It closes the snackbar, **but ALSO the dialog.** (we don't want that).
Here are the z-index system of Spark: 
```
zIndex: {
hide: '-1',
base: '0',
raised: '1',
dropdown: '1000',
sticky: '1100',
overlay: '1300',
modal: '1400', // …
```
=> fix(dialog): do not close dialog when foreground elements are clicked

.eslintrc.cjs, packages/utils/theme/src/contrastCheck.doc.mdx, packages/utils/theme/src/contrastCheck.stories.tsx, packages/utils/theme/src/contrastCheck.ts, packages/utils/theme/src/index.doc.mdx, packages/utils/theme/src/index.ts
**TASK**: #2440 
Added utility to `@spark-ui/theme-utils` to check the accessibility of color contrasts in Spark's themes (or custom themes)
=> docs: story page to check color contrasts

packages/utils/theme/src/contrastCheck.ts
For WCAG color contrast check, large text font size is `24`, not `16`.
=> fix(theme-utils): fixed large font size for color contrast check

packages/components/breadcrumb/src/BreadcrumbItem.tsx
Add the `min-w-none` class to `BreadcrumbItem` to ensure text truncation occurs when it's too long relative to the container
=> feat(breadcrumb): update BreadcrumbItem styles

.storybook/main.js, .storybook/preview.jsx, package-lock.json, package.json
**Description:**
We need to remove the `@storybook/addon-styling` package and implement a custom theme decorator for more reliable theme switching in our Storybook setup.
**Reason for change:**
- The current `@storybook/addon-styling` is causing runtime errors (see https://github.com/storybookjs/storybook/issues/29189) in stories that use React hooks (e.g., `useState`, `useEffect`)
- A custom theme decorator will provide more reliable theme switching functionality
=> fix: remove @storybook/addon-styling

.storybook/addons/SkinlessThemeSwitcherHandler.jsx
Our Storybook URLs with anchors are currently not functioning as expected. When a URL contains an anchor (href) to a specific heading on the page, the anchor is being removed upon page load. As a result, the page is not automatically scrolling to the corresponding section.
=> fix: prevent removal of anchors from URLs upon page load

package-lock.json, packages/components/visually-hidden/package.json, packages/components/visually-hidden/src/VisuallyHidden.tsx
**TASK**: [SPA-452](https://jira.ets.mpi-internal.com/browse/SPA-452)
Removing `@radix-ui/visually-hidden` from `VisuallyHidden`.
Radix code was simple enough that we don't need it: https://github.com/radix-ui/primitives/blob/main/packages/react/visually-hidden/src/VisuallyHidden.tsx
=> refactor(visually-hidden): removed radix dependency from VisuallyHidden

packages/components/combobox/src/ComboboxInput.tsx
**TASK**: [SPA-484](https://jira.ets.mpi-internal.com/browse/SPA-484)
`onBlur, onChange, onClick, onKeyDown` all have a prop generated by Downshift.
Because we apply downshift props with higher priority:
```
{...props}
{...downshiftInputProps}}
```
It erases props of the same name passed by the used. In this PR add a third set of props that merges those events:
```
{...mergedEventProps}
```
=> fix(combobox): fuse event callback with downshift on combobox input

package-lock.json, packages/components/visually-hidden/package.json, packages/components/visually-hidden/src/VisuallyHidden.test.tsx, packages/components/visually-hidden/src/VisuallyHidden.tsx
**TASK**: [SPA-485](https://jira.ets.mpi-internal.com/browse/SPA-485)
Missing `asChild` prop on `VisuallyHidden` to make it polymorphic. Until now it was a `span` and could not be any other html tag.
=> feat(visually-hidden): added asChild prop to VisuallyHidden

packages/components/spinner/src/Spinner.tsx
**TASK**: [SPA-486](https://jira.ets.mpi-internal.com/browse/SPA-486)
`span` is more appropriate than `div` for the Spinner, as it can be used inside a `Button` (`div` inside a `button` is invalid HTML)
=> fix(spinner): set spinner as span

packages/utils/theme/src/theme.css
The `⁠--spacing-sz-1` token was computed as 10px instead of 1px
=> fix: update --spacing-sz-1 token

.storybook/main.js
Prevent runtime errors, see https://github.com/storybookjs/storybook/issues/30115
=> fix: prevent sb runtime errors

package-lock.json, packages/components/input/src/InputClearButton.tsx, packages/components/popover/src/PopoverContent.styles.ts
Following Tailwindcss v4 update, some arbitrary classNames are using invalid css variables.
=> fix(popover): fixed invalid ss var in popover className

packages/components/snackbar/src/Snackbar.test.tsx, packages/components/snackbar/src/SnackbarItem.styles.ts, packages/components/snackbar/src/SnackbarItem.tsx
Closes #2567 
Ensure snackbar items are properly read by screen readers.
> [!WARNING]  
While snackbar items are read properly when triggered via the keyboard (using "ctrl+option+spacebar"), they are not read when triggered via a mouse click 🤷
**OS:** macOS Sequoia 15.2  
**Screen reader:** VoiceOver
=> fix(snackbar): ensure toasts are properly read by screen readers

packages/components/slider/src/Slider.doc.mdx, packages/components/slider/src/Slider.stories.tsx
We forgot to add a story explaining the controlled props for `@spark-ui/slider`
=> docs(slider): added controlled mode story for slider

package-lock.json, packages/components/accordion/package.json, packages/components/accordion/src/Accordion.tsx, packages/components/collapsible/package.json, packages/components/collapsible/src/Collapsible.tsx, packages/components/pagination/package.json, packages/components/pagination/src/PaginationContext.tsx
Update Spark components to use the latest stable version (v1) of zag.js following its official release
=> chore: upgrade zag.js to v1

documentation/Tokens.mdx, documentation/helpers/TokenPreview/index.tsx
Display of some tokens was not easily readable as it shows the raw value of the css variables: `calc(.25rem*calc(16/16))`.
Adding a trick to get computed style from a real DOM element to display the values in pixels.
Before:
After:
=> docs: computed design token values from real styles

.github/workflows/release.yml
Removed automation of Contributors.md through a GH Action (broken after repo transfer)
=> ci: removed contributors gh action

.github/CODEOWNERS, .github/dependabot.yml
Some people belonged to `adevinta` org, and the repo has been transfered to `leboncoin`.
In order to avoid error messages in the dependabot PRs, I must remove them from the list (they could be re-added later by joining the `leboncoin` org)
=> chore: removed former spark members from dependabot reviewers

package-lock.json, packages/utils/cli/package.json, packages/utils/cli/src/core/System.mjs, packages/utils/cli/src/generate/generators/TemplateGenerator.mjs
`glob` package was used in only two files, for internal usage in Spark to generate new packages. It was 3 major versions late and updating it breaks things, I prefer to get rid of it for now.
=> chore: removed usage of glob package

.github/dependabot.yml
Fine-tuned dependabot settings:
- grouping weekly updates in a single PR.
- only assigning @Powerplex as reviewer (core maintainer going forward).
- **no longers ignores major updates**
=> ci: dependabot will no longer ignore major versions of deps

packages/components/package.json, packages/components/tsup.config.ts
Isolate the code of `form-field` during the build so it is not repeated in every component `dist`
=> fix: isolate form-field code to be shared across components

packages/components/src/combobox/ComboboxInput.tsx, packages/components/src/combobox/tests/withFormField.test.tsx, packages/components/src/form-field/FormField.test.tsx, packages/components/src/form-field/FormFieldStateMessage.tsx
**TASK**: [SPA-598](https://jira.ets.mpi-internal.com/browse/SPA-598)
The input of the combobox is a custom one, not using `@spark-ui/input`.
`@spark-ui/input` is using the `FormField` context through `useFormFieldControl` to be linked properly to it's label/messages.
We forgot to use this hook in `Combobox.Input`.
**note**: also removes the `aria-live="polite"` from all `FormField` messages, as it is bad for a11y to read out loud message updates.
=> fix(components): fixed accessible description on combobox input

packages/components/src/progress/Progress.doc.mdx, packages/components/src/progress/Progress.stories.tsx, packages/components/src/progress/Progress.tsx
**TASK**: [SPA-565](https://jira.ets.mpi-internal.com/browse/SPA-565)
- allow `Progress` to be focusable programatically.
- guidance to properly manage focus forwarding when using a progress bar.
- updated references to the wrong W3C pattern (Meter) top `progressbar` role.
https://github.com/user-attachments/assets/8a49cba0-74c8-45ef-aba6-ec238c60616f
=> feat(components): progress - screen reader optimization

packages/components/src/combobox/Combobox.doc.mdx, packages/components/src/combobox/Combobox.stories.tsx, packages/components/src/combobox/ComboboxContext.tsx
**TASK**: [SPA-626](https://jira.ets.mpi-internal.com/browse/SPA-626)
Realistically, combobox items are often loaded asynchronously after a call to a service.
- It means The input of the combobox has no access to the items values and labels.
- It means the input CAN'T display the selected item label until the data is loaded, it will just display the placeholder until it is.
The bug is:
once the items are loaded/rendered, the input does not sync with it and remains empty instead of showing the selected item label, giving the user the impression that no value is selected.
=> fix(components): combobox - sync async options load  with input

documentation/helpers/AriaRole/index.tsx, documentation/helpers/AriaRole/rolesDescriptions.ts, documentation/helpers/AriaRoles/index.tsx, package-lock.json, package.json, packages/components/src/accordion/Accordion.doc.mdx, packages/components/src/button/Button.doc.mdx
New helper components for MDX documentation: `AriaRole` and `AriaRoles`.
Used to display details about aria roles used by each part of a Spark's compound component.
=> docs(components): aria role cards in mdx

packages/components/src/input/Input.styles.ts
Bugfix: the native autocomplete feature of webkit browsers is using its own text node which did not inherit from the font color that we set. A custom selector must be used instead.
https://github.com/user-attachments/assets/08fadb3c-3926-4320-8f60-1f2d514aa7a9
=> fix(components): fixed text color of input native autocomplete text

e2e/a11y/pages/Tabs.tsx, packages/components/src/carousel/useCarousel.ts, packages/components/src/combobox/ComboboxEmpty.tsx, packages/components/src/combobox/ComboboxInput.tsx, packages/components/src/tabs/Tabs.doc.mdx, packages/components/src/tabs/Tabs.stories.tsx, packages/components/src/tabs/Tabs.test.tsx, packages/components/src/tabs/TabsList.tsx
- streamlined stories for `Tabs` (some code was shared between stories)
- disabled `aria-live="polite"` on the `Carousel` when it has multiple slides per page.
- removed `aria-haspopup` from combobox (inherited from the `Popover`, it is already implicit with the `combobox` role and makes things too verbose when using a screen reader)
- updated `Combobox.Empty` to be a `li` instead of a `div` as the HTML markup was invalid.
=> Combobox a11y updates

packages/components/src/dialog/DialogOverlay.tsx, packages/components/src/drawer/DrawerOverlay.tsx, packages/utils/theme/src/dark-theme.css
Two updates to improve contrast of overlay for `Dialog` and `Drawer` components:
- update the color token for the dark theme.
- fixed the opacity applied to the overlay color (`dim-3` -> `dim-1`)
=> fix(components): update overlay color for dialogs

.storybook/manager.js, documentation/references/ComponentDeps.mdx
`Base UI` is a new UI library made by both members of Radix UI and Material. They aim to maintain it over a long period of time and it covers:
- Radix components, and they aim to re-use a very similar API to avoid breaking changes.
- Will get more and more components in the future.
I see it as a replacement for Radix UI implementations, with one major change: polymorphic components stops using `asChild` prop and uses `render` props now.
I am adding this table to get a clear view of what components we could migrate first, and also in the future maybe Base UI could help us get rid of ZagJS and/or React-aria (nothing against these, I just prefer not to be dependant on too many component libraries)
=> docs: mdx table to check for components main library deps

packages/components/src/form-field/FormField.doc.mdx, packages/components/src/form-field/FormField.stories.tsx, packages/components/src/form-field/FormFieldCharactersCount.tsx, packages/components/src/input/Input.stories.tsx, packages/components/src/textarea/Textarea.stories.tsx
**TASK**: [SPA-650](https://jira.ets.mpi-internal.com/browse/SPA-650)
Added `description` and `liveAccouncement` props on `FormField.CharactersCount` for a better screen reader support.
=> feat(components): formfield chars count now support screen readers

packages/utils/theme/vite.config.ts
Vite v6 migration renamed the css output from `style.css` to `index.css` which was breaking for spark usage:
```
@import './node_modules/@spark-ui/theme-utils/dist/style.css';
```
=> fix(theme-utils): css output was no longer named style.css

packages/components/src/combobox/ComboboxItem.tsx
Closes #2712 
Props were forwarded inside `Combobox.Item`, but only in the wrapper/context provider, not on the component underneath it, so the props were lost.
=> fix(components): forward props to ComboboxItem

packages/components/src/stepper/Stepper.stories.tsx, packages/components/src/stepper/Stepper.test.tsx, packages/components/src/stepper/Stepper.tsx, packages/components/src/stepper/StepperButton.tsx, packages/components/src/stepper/types.ts
=> refactor(components): remove useless types and cleanup

.storybook/ThemeProvider.tsx, .storybook/preview-head.html, .storybook/preview.tsx, packages/utils/theme/src/dark-theme-more-contrast.css, packages/utils/theme/src/light-theme-more-contrast.css, packages/utils/theme/src/theme.css
Introducing high contrast colors for Spark UI, for both light/dark color schemes.
Spark will now have 4 set of colors (themes) offered by default:
```
data-theme="light"
data-theme="light-more-contrast"
data-theme="dark"
data-theme="dark-more-contrast"
```
As light/dark have know contrast issues regarding some colors (ex: `main` color on light mode), the high contrast variant provides sufficient contrast to satisfy WCAG criterias.
https://github.com/user-attachments/assets/4104e9a0-0f06-4c50-88d2-89eb33aab6db
=> feat(theme-utils): high-contrast-mode

packages/components/src/carousel/CarouselControls.tsx
Fixes #2732 
Forwarding `className` (and base html attributes) to `Carousel.Controls` to allow customization.
=> fix(components): forward props to CarouselControls

packages/utils/theme/src/dark-theme-more-contrast.css, packages/utils/theme/src/light-theme-more-contrast.css
**TASK**: [LBCSPARK-53](https://jira.ets.mpi-internal.com/browse/LBCSPARK-53)
The "support" intent in dark mode + high contrast appeared "lighter" than the others. This was an error since this is not the case in light mode. 
The "surface-inverse-hovered" in high contrast + light mode was not correct and almost the same color as on-surface-inverse (the text color), which made the text invisible on hover.
=> fix(theme-utils): invalid color tokens in high contrast mode

packages/components/src/checkbox/Checkbox.doc.mdx, packages/components/src/checkbox/Checkbox.stories.tsx, packages/components/src/radio-group/RadioGroup.doc.mdx, packages/components/src/radio-group/RadioGroup.stories.tsx
Closes [LBCSPARK-261](https://jira.ets.mpi-internal.com/browse/LBCSPARK-261)
Closes [LBCSPARK-262](https://jira.ets.mpi-internal.com/browse/LBCSPARK-262)
UI suggested a new design/guideline for the custom radio/checkbox groups examples.
=> docs(components): new design for custom checkbox and radio example

packages/components/src/checkbox/Checkbox.doc.mdx, packages/components/src/checkbox/Checkbox.stories.tsx, packages/components/src/checkbox/CheckboxInput.styles.ts, packages/components/src/radio-group/RadioGroup.doc.mdx, packages/components/src/radio-group/RadioGroup.stories.tsx, packages/components/src/radio-group/RadioInput.styles.ts
Closes JIRA [LBCSPARK-259](https://jira.ets.mpi-internal.com/browse/LBCSPARK-259)
Closes JIRA [LBCSPARK-260](https://jira.ets.mpi-internal.com/browse/LBCSPARK-260)
On both `Radio` and `Checkbox`:
- only `basic` and `error` intents remains documented (NOTE: the other intents are not removed to avoid a breaking change, but should no longer be used)
- `error` intent now display a red outline even in unchecked state (vs "outline" color before the changes)
- the `reverse` prop documentation has been removed, as for `a11y` this is not something we want to encourage.
=> fix(components): update design checkbox

packages/components/src/progress-tracker/ProgressTrackerStep.styles.ts, packages/components/src/progress-tracker/ProgressTrackerStepLabel.styles.ts, packages/components/src/progress-tracker/ProgressTrackerStepLabel.tsx, packages/components/src/progress-tracker/stepIndicatorVariants/outline.ts, packages/components/src/switch/Switch.doc.mdx, packages/components/src/switch/Switch.stories.tsx, packages/components/src/switch/SwitchInput.styles.ts, packages/components/src/tabs/TabsTrigger.styles.ts
- Fixes [LBCSPARK-327](https://jira.ets.mpi-internal.com/browse/LBCSPARK-327)
- Fixes [LBCSPARK-333](https://jira.ets.mpi-internal.com/browse/LBCSPARK-333)
- Fixes [LBCSPARK-330](https://jira.ets.mpi-internal.com/browse/LBCSPARK-330)
- Switch: Improved contrast when unchecked (adjusted opacity of background and icon)
- ProgressTracker: 
- Improved contrast of the active step for the `outline` design.
- Line that links the step together is now using `outline` color token instead of various colors.
- Text of the active step is now bold.
- Tabs: active tab trigger's text is now bold
before/after
=> fix(components): contrast improvements

packages/components/src/combobox/ComboboxTrigger.styles.tsx, packages/components/src/dropdown/DropdownTrigger.styles.tsx, packages/components/src/input/Input.styles.ts, packages/components/src/select/SelectTrigger.styles.tsx, packages/components/src/slider/SliderThumb.styles.ts, packages/utils/theme/src/dark-theme-more-contrast.css, packages/utils/theme/src/dark-theme.css, packages/utils/theme/src/light-theme-more-contrast.css, packages/utils/theme/src/light-theme.css, packages/utils/theme/src/theme.css, packages/utils/theme/src/utilities.css
Keyboard focus was mostly using `--color-blue`, expect on the following components: `Stepper, Input, Textarea, Select, Dropdown, Combobox`. For a more cohesive navigation we decided to update them to the same outline color as other components.
=> style(components): use blue outline for input keyboard navigation

packages/components/src/tag/Tag.doc.mdx, packages/components/src/tag/Tag.stories.tsx, packages/components/src/tag/Tag.styles.tsx, packages/components/src/tag/Tag.tsx, packages/components/src/tag/variants/default.ts, packages/components/src/tag/variants/filled.ts, packages/components/src/tag/variants/outlined.ts, packages/components/src/tag/variants/tinted.ts
- Added `size` prop.
- `md` size (default) is 20px.
- `lg` size (new) is 24px.
- Added custom example for shape (`rounded-no-bl`)
=> feat(components): tag shapes and sizes

packages/components/src/carousel/Carousel.doc.mdx, packages/components/src/carousel/Carousel.stories.tsx, packages/components/src/carousel/Carousel.test.tsx, packages/components/src/carousel/Carousel.tsx, packages/components/src/carousel/CarouselPageIndicator.tsx, packages/components/src/carousel/CarouselPagePicker.tsx, packages/components/src/carousel/types.ts, packages/components/src/carousel/useCarousel.ts, packages/components/src/carousel/utils.ts, packages/components/src/dialog/Dialog.stories.tsx
**TASK**: [LBCSPARK-370](https://jira.ets.mpi-internal.com/browse/LBCSPARK-370)
New prop for `Carousel`: `maxDots` (default: 5).
set to `Infinity` (number) to display all page indicators (dots). DOES NOT WORK if you use custom page indicators (you will have access to the `data-state` attribute to style it yourself)
https://github.com/user-attachments/assets/4f03f734-6d24-404a-a507-17e516ef8535
=> feat(components): maxDots on carousel

packages/utils/theme/src/dark-theme.css
Contrast effect of `surface-hovered` was too strong in dark mode theme.
=> fix(theme-utils): improved surface hover color token

packages/components/src/button/variants/contrast.ts, packages/components/src/button/variants/ghost.ts
**TASK**: [LBCSPARK-409](https://jira.ets.mpi-internal.com/browse/LBCSPARK-409)
Update both `contrast` and `ghost` buttons design. Text color switches from `main` to `on-main-container` (a token that semantically more appropriate for text and provides better contrast.
=> style(components): improved text contrast on ghost and contrast buttons

documentation/helpers/TokenPreview/index.tsx, documentation/styling/Tokens.mdx, packages/utils/theme/src/theme.css
- Added missing `inset-*` version of the shadow tokens.
- Added tokens preview for shadows and "rings" in the Tokens page (Storybook).
=> Improve shadow tokens

documentation/styling/Tokens.mdx, packages/utils/theme/src/theme.css
- Adding `dim-full` token for opacity (to be aligned with Figma tokens)
- Updated tokens preview in the Tokens MDX
=> docs(theme-utils): adding opacity-none and opacity-0 to tokens doc

packages/components/src/input/InputGroup.tsx
When cloning the input element, the current value was getting lost in scenarios where libraries like **React Hook Form** only expose a `ref` (via the ⁠[register](https://react-hook-form.com/docs/useform/register) method) without providing direct access to the input value.
Retrieve the current value from ⁠inputRef.current?.value before cloning the input to ensure the value is preserved and passed correctly.
=> fix(components): preserve input value from ref when cloning
