pull_request_template.md

`❓ Ask`
**TASK**: #170
In order to standarize the PR structure of each contribution

chore(root): ADD pr-template

---

.github/workflows/quality.yml
.github/workflows/release.yml
packages/components/button/src/Button.tsx

**TASK**: #196
This PR adds package publishing into the CI when something is pushed to master

ci: add release ci

---

config/component.ts

Linting was throwing an error because of require() used inside a module

fix: fixed linting of vite component vonfig

---

documentation/contributing/TestingStrategy.mdx

**TASK**: #200 
First version of guidelines regarding packages testing (components and utilities). It's a first version and we should discuss it together and update it.

docs: testing guidelines

---

lerna.json
packages/components/dummy/package.json

All the new packages need to have the flag `--access public` to be published.

fix: new package access

---

.github/workflows/manual-deploy.yml
.github/workflows/quality.yml
.github/workflows/release.yml

ci: deployments on the workflow

---

documentation/contributing/CommitStrategy.mdx

**TASK**:  #210 
Commit convention, enforcing convention, lerna integration and fuerther reading topics are covered in the commit documentation

docs: document commit strategy

---

.lintstagedrc.json

feat: update lintstaged config to englobe more file extensions

---

documentation/helpers/StoryHeading/index.tsx
documentation/helpers/StoryHeading/styles.module.css

feat: implement scrolling to a specified id on page load for urls containing an id

---

createThemeConfig.ts
package-lock.json
package.json
packages/utils/theme-node/.npmignore
packages/utils/theme-node/package.json
packages/utils/theme-node/src/createCSSTokensFile.ts
packages/utils/theme-node/src/createTailwindThemeConfigFile.ts
packages/utils/theme-node/src/index.ts
packages/utils/theme-node/src/utils.ts
packages/utils/theme-node/tsconfig.json
packages/utils/theme-node/vite.config.ts
packages/utils/theme/src/index.stories.mdx
packages/utils/theme/src/index.ts

BREAKING CHANGE: Split the theme utils package into two distinct packages #235
**TASK**: #235
Split this package into two distinct ones: one for Node.js usage and the other for browser consumption

feat: split the theme utils package into two distinct packages

---

.github/workflows/quality.yml
.gitignore
createThemeConfig.ts
package.json

**TASK**: #239 
This PR adds type checking command and integrate it to the CI

chore: add typechecking

---

package-lock.json
package.json
packages/utils/cli/bin/spark-generate.mjs
packages/utils/cli/package.json
packages/utils/cli/utils.js

make the spark generate command more user-friendly
closes #237
**TASK**: #237
We introduce a prompt system before introducing new templates. For now only "component" template is ready to be used, next one will be "hook".
https://user-images.githubusercontent.com/2033710/218986825-be60669b-df60-48d2-a2bd-6bffa0e40d37.mov

feat(cli-utils): prompt system for spark generate command

---

documentation/build/Build.mdx

Define basic Vite build configuration and where can be found
4
**TASK**:

docs: add build documentation

---

package-lock.json
packages/utils/theme-node/package.json
packages/utils/theme-node/src/createCSSTokensFile.ts
packages/utils/theme-node/src/createTailwindThemeConfigFile.ts
packages/utils/theme-node/src/utils.ts
packages/utils/theme-node/vite.config.ts

refactor(theme-utils-node): clean up code

---

package-lock.json
packages/utils/theme-node/package.json
packages/utils/theme-node/src/createCSSTokensFile.ts
packages/utils/theme-node/src/createTailwindThemeConfigFile.ts

Fix broken package build in CI
#257
https://github.com/adevinta/spark/actions/runs/4205837449/jobs/7298494741

fix: broken package build in ci

---

documentation/practices/Naming.mdx

fix: naming practices

---

package.json
packages/utils/cli/bin/spark-generate.mjs
packages/utils/cli/src/index.stories.mdx

docs(cli-utils): add documentation for cli utils package

---

package.json
packages/utils/cli/bin/spark-setup-theme.mjs
packages/utils/cli/package.json

fix(cli-utils): cli command was failing

---

packages/utils/cli/src/setup-themes/utils/createTailwindThemeConfigFile.js
packages/utils/cli/src/utils.js

feat(cli-utils): update cli setup-themes functions

---

documentation/getting-started/GettingStarted.mdx

docs: typos

---

packages/utils/cli/src/setup-themes/utils/constants.js

fix(cli-utils): missing export

---

.storybook/main.cjs

feat: set up "Getting Started" page as default landing page

---

documentation/helpers/Alert/index.tsx
global.d.ts

refactor: clean up Alert helper component

---

packages/utils/theme/src/defaultTheme.ts
packages/utils/theme/src/types.ts

Following tailwind implementation I sorted the tokens by alphabetical order.

refactor(theme-utils): sort tokens namespaces alphabetically

---

documentation/getting-started/GettingStarted.mdx
documentation/migration/StyledComponents.mdx

docs: add styled component migration doc

---

packages/utils/cli/src/setup-themes/utils/constants.js
packages/utils/cli/src/setup-themes/utils/createTailwindThemeConfigFile.js

feat(cli-utils): update toTailwindConfig mapper to handle edge cases

---

packages/utils/cli/src/setup-themes/utils/createCSSTokenfile.js

feat(cli-utils): handle overlooked edge cases

---

packages/utils/tailwind-plugins/animation.stories.mdx

docs: fix typo

---

packages/utils/cli/src/setup-themes/utils/createTailwindThemeConfigFile.js
packages/utils/cli/src/setup-themes/utils/utils.js

Update setup-themes transformer functions

feat(cli-utils): update setup-themes transformer functions

---

packages/utils/cli/README.md
packages/utils/tailwind-plugins/README.md
packages/utils/theme/README.md

docs: add missing readme files

---

documentation/migration/StyledComponents.mdx

docs: improve styled-components docs following feedbacks

---

package-lock.json
packages/components/radio/package.json
packages/components/radio/src/Radio.stories.mdx

**TASK**: None
This PR fixes a typo and add missing dep

Feat add cva radio

---

documentation/getting-started/GettingStarted.mdx

**TASK**: None
This PR add tailwindcss radix setup example

docs: add spark for tailwindRadix

---

packages/components/radio/src/Radio.variants.ts

fix(radio): remove outline

---

package-lock.json
packages/utils/tailwind-plugins/package.json

fix wrong package dependency version
#434
**TASK**:

fix(tailwind-plugins): fix package dependency version

---

package-lock.json
package.json

improve our tailwind config viewer, add support for typography related tokens, by replacing tailwind-config-viewer with our own @adevinta/tailwind-config-viewer package
**TASK**: #438

feat: replace tailwind-config-viewer with @adevinta/tailwind-config-viewer

---

packages/utils/tailwind-plugins/sizings/index.js

feat(tailwind-plugins): add min-height and min-width to sizing plugin

---

packages/components/slot/.npmignore
packages/components/slot/package.json
packages/components/slot/src/Slot.doc.mdx
packages/components/slot/src/Slot.stories.tsx
packages/components/slot/src/Slot.test.tsx
packages/components/slot/src/Slot.tsx
packages/components/slot/src/index.ts
packages/components/slot/tsconfig.json
packages/components/slot/vite.config.ts

**TASK**: #448 
This PR adds the slot component which is a wrapper of the radix one

feat(slot): add slot component

---

package-lock.json
packages/components/checkbox/package.json
packages/components/checkbox/src/Checkbox.doc.mdx
packages/components/checkbox/src/Checkbox.stories.tsx
packages/components/checkbox/src/Checkbox.tsx

feat(checkbox): remove hardcoded check icon

---

package-lock.json
package.json

chore: bump to Tailwind@3.3.0

---

documentation/contributing/WritingStories.mdx
documentation/getting-started/GettingStarted.mdx
documentation/helpers/Callout/index.tsx
documentation/migration/StyledComponents.mdx
documentation/practices/ComponentDoD.mdx
documentation/practices/ComponentDoR.mdx
packages/utils/cli/src/index.doc.mdx
packages/utils/tailwind-plugins/animations/index.doc.mdx
packages/utils/tailwind-plugins/index.doc.mdx
packages/utils/tailwind-plugins/sizings/index.doc.mdx
packages/utils/tailwind-plugins/spark-config.doc.mdx
packages/utils/tailwind-plugins/spark-theme/index.doc.mdx
packages/utils/theme/src/index.doc.mdx

refactor: rename Alert to Callout

---

package-lock.json
packages/components/tag/.npmignore
packages/components/tag/package.json
packages/components/tag/src/Tag.doc.mdx
packages/components/tag/src/Tag.stories.tsx
packages/components/tag/src/Tag.styles.tsx
packages/components/tag/src/Tag.test.tsx
packages/components/tag/src/Tag.tsx
packages/components/tag/src/index.ts
packages/components/tag/src/variants/default.ts
packages/components/tag/src/variants/filled.ts
packages/components/tag/src/variants/index.ts
packages/components/tag/src/variants/outlined.ts
packages/components/tag/src/variants/tinted.ts
packages/components/tag/tsconfig.json
packages/components/tag/vite.config.ts

**TASK**: #496 
Tags are used to label content and help users quickly recognize info about them

feat(tag): tag component

---

documentation/helpers/ReactLiveBlock/index.tsx

**TASK**: 
Required to copy-paste icons

chore: export useClipboard internal hook

---

packages/components/icon/src/Icon.stories.tsx
packages/components/icon/src/Icon.tsx
packages/components/icon/src/Icon.variants.tsx
packages/components/switch/src/Switch.stories.tsx
packages/components/switch/src/Switch.tsx
packages/components/switch/src/Switch.variants.tsx

**TASK**: 
get aligned with spark-button size namings (consistency)

fix(icon): redefine size values

---

vite.config.ts

**TASK**: 
This task is to pack the coverage result in each deployment (CI) and also include the lcov output result to add codecov (free OpenSource plan) solution to our PRs
https://about.codecov.io/product/feature/source-code-coverage/
https://about.codecov.io/product/features/
https://about.codecov.io/pricing/

chore: coverage improvements

---

package-lock.json
packages/components/radio/src/Radio.stories.tsx
packages/components/radio/src/Radio.tsx
packages/components/radio/src/Radio.variants.ts
packages/components/radio/src/RadioIndicator.tsx
packages/components/radio/src/RadioIndicator.variants.ts

**TASK**: #531 
This PR:
- Change the way of the size is set for the radio indicator
- Change radio sizes values

feat(radio): size and indicator

---

package-lock.json
packages/hooks/use-combined-state/.npmignore
packages/hooks/use-combined-state/package.json
packages/hooks/use-combined-state/src/index.ts
packages/hooks/use-combined-state/src/useCombinedState.doc.mdx
packages/hooks/use-combined-state/src/useCombinedState.test.tsx
packages/hooks/use-combined-state/src/useCombinedState.tsx
packages/hooks/use-combined-state/tsconfig.json
packages/hooks/use-combined-state/vite.config.ts

**TASK**: 
Sometimes you need to easy handle stateless-statefull behavior of a component
```jsx
import * as React from 'react'
import { useCombinedState } from '@spark-ui/use-combined-state'
const Demo = ({ value, defaultValue, onHandler }) => {
const [
innerValue, // state
setInnerValue, // state setter
isControlledValue, // using controlled behavior or not
initialInnerValue // first inner value state
] = useCombinedState(
value,
defaultValue
)
const handler = event => {
const {target: {value}} = event
setInnerValue(value) // you dnt have to take care if its controlled or not
typeof onHandler === 'function' && onHandler(event, {value})
}
return <element value={innerValue} onHandler={handler} />
}
```

feat(use-combined-state): new hook

---

.github/workflows/quality.yml
.github/workflows/release.yml

**TASK**: None
This PR add cancel current jobs when a new one is created so it won't need to wait

ci: cancel current jobs

---

packages/utils/internal-utils/package.json

Make package publicly accessible on npm (previously private)

feat(internal-utils): make package publicly accessible on npm

---

packages/utils/internal-utils/src/index.ts
packages/utils/internal-utils/src/tw/index.ts
packages/utils/internal-utils/src/variants/constants.ts
packages/utils/internal-utils/src/variants/index.ts
packages/utils/internal-utils/src/variants/types.ts

#546
**TASK**: #546
Add variant utils to manage common component settings

feat(internal-utils): add variants folder

---

packages/components/button/src/Button.doc.mdx
packages/components/button/src/Button.stories.tsx
packages/components/checkbox/src/Checkbox.doc.mdx
packages/components/icon/src/Icon.doc.mdx
packages/components/icons/src/index.doc.mdx
packages/components/icons/src/index.stories.tsx
packages/components/portal/src/Portal.doc.mdx
packages/components/radio/src/Radio.doc.mdx
packages/components/slot/src/Slot.doc.mdx
packages/components/switch/src/Switch.doc.mdx
packages/components/tag/src/Tag.doc.mdx
packages/components/visually-hidden/src/VisuallyHidden.doc.mdx

As we're investigating on Storybook v7 issues, there was some warnings we wanted to clean : missing keys, Canvas usage update, ...

chore: cleaning warning messages from StoryBook

---

packages/utils/cli/src/generate/templates/component/src/[Component.doc.mdx].js

**TASK**:  #562 
Prevent warnings with deprecated usage of Storybook `Canvas` component.

docs: upd canvas usage in storybook

---

.eslintrc.cjs
documentation/helpers/Callout/index.tsx
documentation/helpers/ReactLiveBlock/index.tsx
package-lock.json
package.json
packages/components/button/src/Button.stories.tsx
packages/components/button/src/Button.styles.tsx
packages/components/button/src/variants/filled.ts
packages/components/checkbox/src/Checkbox.stories.tsx
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/Checkbox.variants.tsx
packages/components/icon/src/Icon.stories.tsx
packages/components/icons/src/index.stories.tsx
packages/components/portal/src/Portal.stories.tsx
packages/components/radio/src/Radio.stories.tsx
packages/components/radio/src/Radio.variants.ts
packages/components/radio/src/RadioIndicator.variants.ts
packages/components/switch/src/Switch.stories.tsx
packages/components/switch/src/Switch.variants.tsx
packages/components/tag/src/Tag.stories.tsx
packages/components/tag/src/Tag.styles.tsx
packages/hooks/use-combined-state/src/useCombinedState.tsx
packages/utils/internal-utils/src/index.ts
packages/utils/internal-utils/src/tw/index.ts
packages/utils/internal-utils/src/variants/index.ts
packages/utils/internal-utils/src/variants/types.ts

refactor: clean up code (05-04-23)

---

packages/components/button/src/Button.styles.tsx
packages/components/checkbox/package.json
packages/components/checkbox/src/Checkbox.variants.tsx
packages/components/icon/package.json
packages/components/icon/src/Icon.variants.tsx
packages/components/radio/package.json
packages/components/radio/src/RadioIndicator.variants.ts
packages/components/radio/src/RadioInput.variants.ts
packages/components/switch/src/Switch.variants.tsx
packages/components/tag/package.json
packages/components/tag/src/Tag.styles.tsx

refactor: enforce cohesiveness using @spark-ui/internal-utils

---

packages/utils/theme/package.json

fix(theme-utils): update package deps

---

package-lock.json
packages/utils/theme/src/defaultTheme.ts
packages/utils/theme/src/defaultThemeDark.ts

Synced theme colors with figma values

style(theme-utils): synced colors with figma

---

packages/components/button/package.json
packages/components/checkbox/package.json
packages/components/icon/package.json
packages/components/icons/package.json
packages/components/portal/package.json
packages/components/radio/package.json
packages/components/slot/package.json
packages/components/switch/package.json
packages/components/tag/package.json
packages/components/visually-hidden/package.json
packages/hooks/use-combined-state/package.json
packages/hooks/use-merge-refs/package.json
packages/hooks/use-mounted-state/package.json
packages/utils/cli/src/generate/templates/component/[package.json].js
packages/utils/cli/src/generate/templates/hook/[package.json].js
packages/utils/tailwind-plugins/package.json

Add peer dependencies field to each package

feat: add peer deps field

---

.storybook/preview-head.html
package-lock.json

Custom padding of stories preview was insufficient for small screens

docs: fixed padding of story previews

---

packages/components/radio/src/Radio.doc.mdx

Fixing story issue after SB `Story` deprecation on Canvas

fix(radio): fix radio story canvas not using story component

---

package-lock.json
packages/components/checkbox/package.json
packages/components/icon/package.json
packages/components/icon/src/Icon.tsx
packages/components/icons/package.json
packages/components/switch/package.json
packages/components/tag/package.json
packages/components/visually-hidden/package.json
packages/components/visually-hidden/src/VisuallyHidden.tsx

package versions

---

packages/components/slot/src/Slot.doc.mdx
packages/components/slot/src/Slot.stories.tsx

docs(slot): extend the documentation

---

packages/components/slot/src/Slot.stories.tsx

docs(slot): demo type

---

packages/components/slot/src/Slot.stories.tsx

fix: TS errors causing CI failures

---

packages/utils/tailwind-plugins/spark-theme/index.js
packages/utils/tailwind-plugins/spark-theme/utils.js

Optimize multi-theme handling by eliminating token duplication
**TASK**: #592

feat(tailwind-plugins): optimize multi-theme handling by eliminating token duplication

---

package.json

**TASK**: None
- Change lerna to release based on git history
- Remove some lerna publish not needed params

chore: release packages based on git changes

---

packages/components/spinner/package.json
packages/utils/cli/package.json

Bump versions

---

package.json

chore: remove from-git command

---

packages/components/icon/src/Icon.variants.tsx
packages/utils/tailwind-plugins/index.js
packages/utils/tailwind-plugins/utilities/index.js

Add a new utilities plugin to handle cases not covered by tw default classes

feat(tailwind-plugins): add a new utilities plugin

---

packages/components/checkbox/src/CheckboxInput.styles.ts

**TASK**: #616 
Fix label alignment when there is a multiline text.

fix(checkbox): fix label alignment

---

documentation/getting-started/GettingStarted.mdx
documentation/styling-overview/StylingOverview.mdx
documentation/tailwind-config-viewer/TCV.mdx

**TASK**: #597
Improve Tailwind related documentation

docs(tailwind-plugins): improve Tailwind related documentation

---

packages/utils/tailwind-plugins/animations/index.doc.mdx
packages/utils/tailwind-plugins/animations/index.js

Update default prefix in tw animation plugin

feat(tailwind-plugins): update default prefix in tw animation plugin

---

package-lock.json
package.json
tailwind.config.viewer.cjs
tailwind.config.viewer.misc.cjs

docs: update tailwind config viewer to display custom plugin classes

---

packages/components/button/src/Button.styles.tsx
packages/components/checkbox/src/CheckboxInput.styles.ts
packages/components/radio/src/RadioInput.variants.ts
packages/components/switch/src/SwitchInput.styles.ts
packages/utils/tailwind-plugins/utilities/index.js
tailwind.config.viewer.misc.cjs

**TASK**: #676
Add new "shadow-border-transition" utility class for handling common transitions across multiple components

feat(tailwind-plugins): add new "shadow-border-transition" utility class

---

packages/components/button/src/Button.styles.tsx
packages/components/checkbox/src/CheckboxInput.styles.ts
packages/components/icon/src/Icon.variants.tsx
packages/components/radio/src/RadioInput.variants.ts
packages/components/switch/src/SwitchInput.styles.ts
packages/utils/tailwind-plugins/utilities/index.js
tailwind.config.viewer.misc.cjs

**TASK**: #679
prefix all added utility classes with `u-*` for consistency and ease of discoverability and intellisense

refactor: prefix all added utility classes with u for consistency and ease of discoverability and intellisense

---

.storybook/main.cjs
package-lock.json

This is mostly a prerequisite task before adding compound components stories documentation. You can see details on documentation [here](https://github.com/styleguidist/react-docgen-typescript#options).

chore: upd ts docgen configuration to improve parsed results

---

packages/components/button/package.json
packages/components/checkbox/package.json
packages/components/icon-button/package.json
packages/components/icon/package.json
packages/components/icons/package.json
packages/components/portal/package.json
packages/components/radio/package.json
packages/components/slot/package.json
packages/components/spinner/package.json
packages/components/switch/package.json
packages/components/tag/package.json
packages/components/visually-hidden/package.json
packages/hooks/use-combined-state/package.json
packages/hooks/use-merge-refs/package.json
packages/hooks/use-mounted-state/package.json
packages/utils/cli/package.json
packages/utils/cli/src/generate/templates/component/[package.json].js
packages/utils/cli/src/generate/templates/hook/[package.json].js
packages/utils/cli/src/generate/templates/util/[package.json].js
packages/utils/internal-utils/package.json
packages/utils/tailwind-plugins/package.json
packages/utils/theme/package.json

chore: add package license, bugs url and homepage

---

packages/utils/cli/test/spark-generate.test.ts

fix(cli-utils): fix tests

---

LICENSE

chore: update license owner

---

documentation/getting-started/GettingStarted.mdx
documentation/migration/StyledComponents.mdx
documentation/styling-overview/StylingOverview.mdx

docs: improve onboarding docs

---

.github/CODEOWNERS

**TASK**: #711 
I really don't know what I'm doing here...

chore: adding JP to spark code owners

---

packages/components/button/src/Button.stories.tsx
packages/components/button/src/Button.styles.tsx
packages/components/button/src/variants/contrast.ts
packages/components/button/src/variants/filled.ts
packages/components/button/src/variants/ghost.ts
packages/components/button/src/variants/outlined.ts
packages/components/button/src/variants/tinted.ts

feat(button): add info intent to all designs

---

.github/workflows/release.yml

When publication job fails, a duplicate tag issue throws on re-running... https://github.com/lerna/lerna/issues/2542

ci: upd lerna workflow to avoid duplicate tags

---

packages/components/visually-hidden/package.json

chore: update CI

---

packages/utils/tailwind-plugins/index.js
packages/utils/tailwind-plugins/tailwind.config.viewer.misc.js
tailwind.config.viewer.cjs

docs(tailwind-plugins): expose tcv misc object

---

package-lock.json
packages/components/label/.npmignore
packages/components/label/package.json
packages/components/label/src/Label.doc.mdx
packages/components/label/src/Label.stories.tsx
packages/components/label/src/Label.test.tsx
packages/components/label/src/Label.tsx
packages/components/label/src/index.ts
packages/components/label/tsconfig.json
packages/components/label/vite.config.ts

feat(label): add label component

---

packages/components/tabs/src/index.ts

As suggested by @andresz1 [here](https://github.com/adevinta/spark/pull/758#discussion_r1192047598), we want to ship our components with related interfaces and/or types.

refactor(tabs): add types export for tabs component

---

.storybook/preview-head.html
documentation/GettingStarted.mdx
documentation/using-spark/Setup.mdx
documentation/using-spark/StylingOverview.mdx
documentation/using-spark/TCV.mdx

docs: update docs with minor tweaks and improvements

---

documentation/using-spark/StyledComponents.mdx

docs: add "polymorphic" doc section

---

.github/workflows/release.yml

**TASK**: #594 
This PR attends to identify the release bot so we can skip the security checks only for the bot

ci: identify the release bot

---

.github/workflows/release.yml

ci: use service account

---

.storybook/preview-head.html
packages/utils/theme/src/defaultTheme.ts
packages/utils/theme/src/types.ts

feat(theme-utils): updated default font name and fallbacks

---

package-lock.json
packages/utils/cli/package.json
packages/utils/cli/test/spark-generate.test.ts

**TASK**: #710
Start executing the test again.

710 spark generate test

---

.github/workflows/release.yml

**TASK**: 
This PR updates the ci to use SA to update contributors and maintainers

ci: use service account to contributors and maintainers

---

package-lock.json
packages/components/form-field/package.json
packages/components/popover/package.json
packages/components/spinner/package.json

**TASK**: #845 
We need to streamline the way we deal with our dependencies inside each package.json of each component. Currently, we sometimes use fixed versions and sometimes use range (^) versions, which can be confusing.
We should review all package.json files and ensure consistency in dependency handling according to the agreement located in our [wiki](https://github.com/adevinta/spark/wiki/Agreements#managing-dependencies-within-spark-components).

chore: harmonize deps rules

---

documentation/GettingStarted.mdx
documentation/using-spark/HandlingThemes.mdx

**TASK**: #849
Add documentation on how to handle multiple themes

docs: add documentation on how to handle multiple themes

---

.eslintrc.cjs
documentation/helpers/ReactLiveBlock/index.tsx
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxGroup.tsx
packages/components/form-field/src/FormField.test.tsx
packages/components/form-field/src/FormFieldProvider.tsx
packages/components/icons/src/index.ts
packages/components/icons/src/tags.ts
packages/components/slot/src/Slot.stories.tsx
packages/components/slot/src/Slot.test.tsx
packages/hooks/use-combined-state/src/useCombinedState.test.tsx
packages/hooks/use-merge-refs/src/useMergeRefs.test.tsx
packages/hooks/use-merge-refs/src/useMergeRefs.tsx
packages/utils/tailwind-plugins/spark-theme/getCSSVariableDeclarations.js
packages/utils/tailwind-plugins/spark-theme/getCSSVariableReferences.js
packages/utils/tailwind-plugins/spark-theme/index.js
packages/utils/tailwind-plugins/spark-theme/utils.js
tailwind.config.viewer.cjs

**TASK**: #858
Address eslint warnings

feat: address eslint warnings

---

package-lock.json
packages/components/popover/package.json
packages/components/popover/src/Popover.test.tsx

**TASK**: #869 
Experimental Popover package was missing unit tests.

test(popover): set of tests for Popover package

---

packages/components/input/src/index.ts

Needed export for the new `text-field` component.

feat(input): export a needed hook

---

package-lock.json
package.json
packages/components/popover/src/Popover.doc.mdx
packages/components/popover/src/Popover.stories.tsx
packages/components/popover/src/Popover.test.tsx
packages/components/popover/src/Popover.tsx
packages/components/popover/src/PopoverPortal.tsx

feat(popover): popover portal subcomponent

---

.eslintrc.cjs

feat: add eslint rules overrides

---

package-lock.json
packages/components/button/package.json
packages/components/button/src/Button.doc.mdx
packages/components/button/src/Button.stories.tsx
packages/components/button/src/Button.test.tsx
packages/components/button/src/Button.tsx
packages/components/icon-button/src/IconButton.doc.mdx
packages/components/icon-button/src/IconButton.stories.tsx
packages/components/icon-button/src/IconButton.tsx
packages/components/slot/src/Slot.tsx
packages/components/spinner/src/Spinner.styles.tsx
packages/components/spinner/src/Spinner.tsx

**TASK**: #539
- [x ] ✨ New feature (non-breaking change which adds functionality)
https://github.com/adevinta/spark/assets/2033710/b55435e3-c2d2-421c-8e03-4b7d72bce473

539 components button loading state

---

packages/utils/tailwind-plugins/spark-theme/constants.js
packages/utils/tailwind-plugins/spark-theme/getCSSVariableReferences.js

feat(tailwind-plugins): motion tokens

---

package-lock.json
packages/components/form-field/package.json
packages/components/label/package.json
packages/components/radio-group/package.json

Previous Radix Label update (minor...) broke our library. As classical revert didn't seem to be an option, we want here to manually undo these changes.

fix: undo radix label bump

---

package-lock.json
packages/components/button/src/Button.styles.tsx
packages/utils/tailwind-plugins/index.js
packages/utils/tailwind-plugins/variants/index.js

feat(tailwind-plugins): spark plugin css retina screens selector

---

packages/components/form-field/src/FormField.tsx
packages/components/input/src/Input.stories.tsx
packages/components/radio-group/src/RadioGroup.styles.ts
packages/components/text-field/src/TextField.stories.tsx

**TASK**: #932 
This PR updates `FormField` spacing according to design specs

feat: update form field spacing

---

.github/workflows/quality.yml
bin/check-a11y.js
package-lock.json
packages/components/switch/src/Switch.stories.tsx
packages/components/tabs/src/Tabs.stories.tsx

To improve CI, we want to run a11y check only for changed components

ci: uses incremental checking

---

.github/workflows/quality.yml

Small (?) improvement to avoid CI to execute unnecessary jobs (if changes aren't about packages/components).

perf: a11y quality workflow made conditional

---

.github/workflows/quality.yml

Silly typo on a11y CI job condition...

ci: fix conditionnal tasks for a11y job (wrong key)

---

documentation/GettingStarted.mdx
documentation/helpers/FAQ/Answer.tsx
documentation/helpers/FAQ/Item.tsx
documentation/helpers/FAQ/Question.tsx
documentation/helpers/FAQ/Root.tsx
documentation/helpers/FAQ/context.tsx
documentation/helpers/FAQ/index.tsx
documentation/using-spark/FAQ.mdx

**TASK**: #949 
We've noticed that certain questions come up frequently in the Slack support channel.
To address these questions more efficiently and provide better support to Spark consumers, we'd like to start filling up the FAQ section with these common questions and their answers.

docs: fill up FAQ section with common questions

---

package-lock.json
package.json

**TASK**: #967 
Update tcv package to be able to display position-related tokens

feat: update tcv package to be able to display position-related tokens

---

packages/components/chip/package.json
packages/components/chip/src/Chip.stories.tsx
packages/components/chip/src/Chip.styles.tsx
packages/components/chip/src/Chip.tsx
packages/components/chip/src/ChipClearButton.styles.tsx
packages/components/chip/src/ChipClearButton.tsx
packages/components/chip/src/index.ts
packages/components/chip/src/useChipContext.tsx
packages/components/chip/src/useChipElement.tsx

feat(chip): add element and clear button

---

packages/components/spinner/package.json
packages/components/visually-hidden/package.json

fix: typo in peerDependency package name, from tailwind to tailwindcss

---

package-lock.json
packages/components/button/src/Button.styles.tsx
packages/components/input/src/Input.stories.tsx
packages/components/input/src/Input.styles.tsx
packages/components/input/src/Input.tsx
packages/components/input/src/InputAddon.styles.ts
packages/components/input/src/InputAddon.tsx
packages/components/input/src/InputGroup.tsx
packages/components/input/src/InputGroupContext.ts
packages/components/input/src/InputLeadingAddon.tsx
packages/components/input/src/InputTrailingAddon.tsx
packages/components/textarea/src/Textarea.stories.tsx

**TASK**:  #1000 
This PR is to refine the styles of addons, especially focus and hover styles, and their combination with disabled state.
We make use of `ring-inset` and replaced border by `ring` (box-shadow) for a better look and feel.
https://github.com/adevinta/spark/assets/2033710/d8931b33-f1df-46ed-8826-37f75a252450

Feat input addon

---

packages/components/checkbox/src/Checkbox.doc.mdx
packages/components/checkbox/src/Checkbox.stories.tsx
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxInput.styles.ts
packages/components/radio-group/src/Radio.tsx
packages/components/radio-group/src/RadioGroup.doc.mdx
packages/components/radio-group/src/RadioGroup.stories.tsx
packages/components/radio-group/src/RadioInput.styles.ts

**ISSUES**: #994 #996
Fix multiline labeled inputs as defined in specs.

[FIX] multiline labeled inputs

---

documentation/using-spark/FAQ.mdx

Add a question to the FAQ section of the documentation about how to handle multiple themes in a project

docs: add question to faq section

---

packages/components/input/src/Input.doc.mdx
packages/components/input/src/Input.stories.tsx
packages/components/input/src/Input.test.tsx
packages/components/input/src/InputGroupContext.ts
packages/components/input/src/InputStateIndicator.tsx

**TASK**: #1014 
This PR:
- Input state indicator tests
- Small changes in the documentation

1014 input state indicator tests

---

.eslintrc.cjs
documentation/helpers/ArgTypes/index.tsx
lerna.json
nx.json
package-lock.json
package.json
packages/components/popover/src/PopoverCloseButton.tsx
packages/components/popover/src/PopoverHeader.tsx
tsconfig.json

**TASK**: #1023 
Updating lerna + NX to benefit from nx eslint rules. This automatically checks for circular deps using `nx graph` json output.

Lerna repair

---

packages/components/chip/src/Chip.stories.tsx
packages/components/chip/src/Chip.styles.tsx
packages/components/chip/src/Chip.tsx
packages/components/chip/src/ChipClearButton.styles.tsx
packages/components/chip/src/ChipContent.tsx
packages/components/chip/src/ChipLeadingIcon.tsx
packages/components/chip/src/index.ts

feat(chip): Stage 4 Leading Icon

---

documentation/using-spark/FAQ.mdx

docs: add faq questions

---

packages/components/checkbox/src/CheckboxLabel.styles.ts
packages/components/radio-group/src/RadioLabel.styles.tsx

feat: update radio/checkbox styles to allow full label width

---

packages/components/chip/src/Chip.doc.mdx
packages/components/chip/src/Chip.stories.tsx
packages/components/chip/src/Chip.styles.tsx
packages/components/chip/src/Chip.tsx
packages/components/chip/src/useChipElement.tsx

🐤 Chip stage 5

---

package-lock.json
packages/components/form-field/src/FormField.tsx
packages/components/form-field/src/FormFieldContext.tsx
packages/components/form-field/src/FormFieldControl.tsx
packages/components/form-field/src/FormFieldLabel.tsx
packages/components/form-field/src/FormFieldProvider.tsx
packages/components/input/src/Input.doc.mdx
packages/components/input/src/Input.stories.tsx
packages/components/input/src/Input.tsx
packages/components/input/src/InputGroup.tsx

**TASK**: #1066 
See attached issue

feat(form-field): disabled styles on label

---

package-lock.json
packages/components/badge/package.json
packages/components/button/package.json
packages/components/icon/package.json
packages/components/spinner/package.json
packages/components/visually-hidden/package.json

We forgot to move those components outside of beta once their specs have been validated

feat: got some beta packages out of beta

---

packages/components/textarea/package.json
packages/components/textarea/src/Textarea.stories.tsx

**TASK**: None
This PR release textarea

feat(textarea): release first version

---

package-lock.json
packages/components/dialog/.npmignore
packages/components/dialog/package.json
packages/components/dialog/src/Dialog.doc.mdx
packages/components/dialog/src/Dialog.stories.tsx
packages/components/dialog/src/Dialog.test.tsx
packages/components/dialog/src/Dialog.tsx
packages/components/dialog/src/DialogCloseButton.tsx
packages/components/dialog/src/DialogContent.tsx
packages/components/dialog/src/DialogDescription.tsx
packages/components/dialog/src/DialogOverlay.tsx
packages/components/dialog/src/DialogPortal.tsx
packages/components/dialog/src/DialogRoot.tsx
packages/components/dialog/src/DialogTitle.tsx
packages/components/dialog/src/DialogTrigger.tsx
packages/components/dialog/src/index.ts
packages/components/dialog/tsconfig.json
packages/components/dialog/vite.config.ts

**TASK**: #1082 
Setup the compound for the `Dialog` component, using Radix.
I created an Epic for the `Dialog` to follow progress.

1030 components dialog experimental

---

package-lock.json
packages/components/dialog/package.json
packages/components/dialog/src/Dialog.stories.tsx
packages/components/dialog/src/Dialog.test.tsx
packages/components/dialog/src/DialogCloseButton.tsx
packages/components/dialog/src/DialogContent.tsx
packages/components/dialog/src/DialogOverlay.tsx

**TASK**: #1100
Adding just enough styles that the component can be visible and interactive in Storybook for now.
https://github.com/adevinta/spark/assets/2033710/d0407eb2-ba69-4dab-b6d9-284b54c02c68

1100 components dialog base styles

---

documentation/using-spark/FAQ.mdx

**TASK**: #1097 
improve faq section

docs: improve faq section

---

packages/components/alert-dialog/src/AlertDialog.doc.mdx
packages/components/alert-dialog/src/AlertDialog.stories.tsx

**TASK**: #1136 
This PR add initial documentation about `AlertDialog`

docs(alert-dialog): add first iteration

---

package-lock.json

package-lock was unsynced and introduced a TS error for the `Input` package

fix(input): ts error because of invalid package-lock

---

.storybook/main.js
packages/components/spinner/src/Spinner.doc.mdx

**TASK**: #1208 
Updated spinner docs to match latest agreement: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs

docs(spinner): updated docs to match latest agreement

---

packages/components/checkbox/src/Checkbox.doc.mdx
packages/components/checkbox/src/Checkbox.stories.tsx

**TASK**: #1206 
Updating `Checkbox` + `CheckboxGroup` stories to match latest agreement: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs

docs(checkbox): updated stories order to match agreements

---

packages/components/button/src/Button.doc.mdx

**TASK**: #1209
Fixing #1209, updating button stories to match latest agreements

docs(button): update button stories to match guidelines

---

package-lock.json
packages/components/icon-button/src/IconButton.doc.mdx

**TASK**: #1210 
Updated docs to match latest agreements: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs

docs(icon-button): updated docs to match latest agreement

---

package-lock.json
packages/components/popover/src/Popover.doc.mdx
packages/components/popover/src/Popover.stories.tsx

**TASK**: #1207 
Updated docs to match updated agreements: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs

docs(popover): updated docs to match latest agreements

---

.storybook/preview-head.html

fix: fix storybook layout issue on small screens

---

package-lock.json
packages/components/chip/package.json
packages/components/chip/src/Chip.doc.mdx
packages/components/chip/src/Chip.stories.tsx
packages/components/chip/src/Chip.styles.tsx
packages/components/chip/src/Chip.tsx
packages/components/chip/src/ChipClearButton.styles.tsx
packages/components/chip/src/ChipClearButton.tsx
packages/components/chip/src/useChipContext.tsx
packages/components/chip/src/useChipElement.tsx
packages/components/chip/src/variants/dashed.ts
packages/components/chip/src/variants/filled.ts
packages/components/chip/src/variants/outlined.ts
packages/components/chip/src/variants/tinted.ts

**TASK**: 
- Fix design with bug
- Apply stage 6 feedback
- Sort stories applying guidelines
- Add keyboard interaction definitions
- Change onClear API to get aligned with what is made in the input package

🐤 Chip Stage 7

---

packages/components/tag/src/Tag.doc.mdx

tag documentation

---

package-lock.json
packages/components/radio-group/src/RadioGroup.doc.mdx
packages/components/radio-group/src/RadioGroup.stories.tsx
packages/components/radio-group/src/RadioGroup.tsx

**TASK**: #1159 
Updated `RadioGroup` docs to match latest agreement: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs

docs(radio-group): updated docs to match latest agreements

---

package-lock.json
packages/components/label/src/Label.doc.mdx

**TASK**: #1247 
Update `Label` docs to align with latest agreements

docs(label): update label docs to match latest requirements

---

package-lock.json
packages/components/tag/src/Tag.doc.mdx

**TASK**: #1164 
Updated `Tag` docs to match latest agreements

docs(tag): updated tag docs to match agreement

---

package-lock.json
packages/components/form-field/src/FormField.doc.mdx
packages/components/form-field/src/FormField.stories.tsx

**TASK**: #1211 
Updated docs to match latest agreements: https://sparkui.vercel.app/?path=/docs/contributing-writing-packages-documentation--docs

docs(form-field): updated docs to match latest agreements

---

package-lock.json
packages/components/alert-dialog/src/AlertDialog.doc.mdx
packages/components/checkbox/src/Checkbox.doc.mdx
packages/components/checkbox/src/Checkbox.stories.tsx
packages/components/switch/src/Switch.doc.mdx
packages/components/switch/src/Switch.stories.tsx
packages/components/switch/src/Switch.tsx
packages/components/switch/src/SwitchInput.tsx
packages/components/switch/src/SwitchLabel.tsx
packages/components/switch/src/index.ts

**TASK**: #1161 
This PR:
- Update checkbox documentation
- Fix missing descriptions in `AlertDialog` and `Checkbox`

feat(switch): add status styles and update docs

---

package-lock.json
package.json

**TASK**: #1213
Add support for displaying z-index related tokens
Implement smooth scrolling to target headings based on URL hash
**z-index support:**
___
**smooth scrolling to target headings based on URL hash:**

feat: bump tailwind-config-viewer to @1.7.7

---

package-lock.json
package.json
packages/utils/tailwind-plugins/tailwind.config.viewer.misc.js

feat: bump tcv to 1.7.9

---

package-lock.json
packages/components/icon/src/Icon.doc.mdx

**TASK**: #1165 
Updated `Icon` docs to match latest agreements

docs(icon): updated docs to match latest agreement

---

package-lock.json
packages/components/input/src/Input.tsx

My bad, I let a `console.log` statement slip during a previous fix.

fix(input): removing console log from input

---

package-lock.json
package.json

**TASK**: #1275
Improve our Tailwind Config Viewer by regrouping colors by section (main, support, accent, etc...) and sorting them.

feat: bump tailwind-config-viewer to @1.8.0

---

packages/components/alert-dialog/src/AlertDialog.test.tsx

**TASK**: #1135 
This PR adds tests to AlertDialog component. Most of them can be used for the Dialog too
Feedback is welcome regarding test organization

test(alert-dialog): add more cases

---

package-lock.json
packages/components/chip/src/Chip.test.tsx
packages/components/chip/src/ChipClearButton.tsx
packages/components/chip/src/useChipElement.tsx

🐤 Stage 8 TEST

---

README.md

ci: Add codecov badge

---

.github/composite-actions/install/action.yml
.github/workflows/quality.yml
nx.json
package-lock.json
packages/components/chip/package.json
packages/components/form-field/src/FormFieldLabel.tsx

**TASK**: #1311 
When rebuilding too many packages, Lerna seems to have some issues...

fix: attempt to fix NX cache configuration with GHA

---

package-lock.json
packages/utils/tailwind-plugins/animations/index.js

- added `slideIn/slideOut` animations to base plugin
- added `fadeIn/fadeOut` animations to base plugin

feat(tailwind-plugins): added base missing keyframe animations

---

packages/components/dialog/src/DialogBody.tsx
packages/components/dialog/src/DialogCloseButton.tsx
packages/components/dialog/src/DialogContent.styles.tsx
packages/components/dialog/src/DialogContent.tsx
packages/components/dialog/src/DialogOverlay.tsx
packages/components/dialog/src/DialogTitle.tsx

**TASK**: #1316 
- open/close animation (fadeIn/fadeOut)
- updated styles to match specs (width, paddings, font-size, etc)
https://github.com/adevinta/spark/assets/2033710/e7aac8e1-c17f-4c2b-a777-bee309458c32

style(dialog): fadeIn animation

---

package-lock.json
packages/components/drawer/src/DrawerContent.styles.tsx
packages/components/drawer/src/DrawerOverlay.tsx

**TASK**: #1318 
- added slideIn/slideOut animations to Spark
- using slideIn/slideOut animations on `@spark-ui/drawer`
https://github.com/adevinta/spark/assets/2033710/433805b2-9ed1-4107-afc0-4631b247c871

style(drawer): drawer slidein animation

---

packages/components/progress/src/Progress.stories.tsx
packages/components/progress/src/ProgressIndicator.styles.ts
packages/components/progress/src/ProgressIndicator.tsx
packages/components/progress/src/ProgressLabel.tsx
packages/utils/tailwind-plugins/animations/index.js

**TASK**: #1342 
This PR updates progress animation

1342 improve progress animation

---

packages/components/slot/src/Slot.doc.mdx
packages/components/slot/src/Slot.stories.tsx

docs(slot): extend documentation including slottable usages

---

package-lock.json
package.json

chore: bump @spark-ui/theme-utils inside root package.json

---

packages/components/progress/src/ProgressIndicator.styles.ts

**TASK**: 
This add missing border radius to progress component. Thanks @elisa-hery

fix(progress): add missing border radius to progress component

---

package-lock.json
package.json

chore: bump TCV to 1.9.0

---

config/component.ts
config/plugins/sparkDocgen.ts
package-lock.json
package.json
packages/components/button/src/Button.tsx

**TASK**: #1354 
Generate docgen of each package at build time to be published under `/dist/public/docgen.json`

chore: generate public docgen for each package

---

packages/components/badge/package.json
packages/components/button/package.json
packages/components/checkbox/package.json
packages/components/chip/package.json
packages/components/dialog/package.json
packages/components/drawer/package.json
packages/components/form-field/package.json
packages/components/icon-button/package.json
packages/components/icon/package.json
packages/components/input/package.json
packages/components/kbd/package.json
packages/components/label/package.json
packages/components/popover/package.json
packages/components/portal/package.json
packages/components/radio-group/package.json
packages/components/spinner/package.json
packages/components/switch/package.json
packages/components/tabs/package.json
packages/components/textarea/package.json

Update the @spark-ui/theme-utils version in the peerDependencies of our components.
The update is necessary to ensure that our components work with the latest version of @spark-ui/theme-utils

chore: update @spark-ui/theme-utils version in peerDependencies

---

.github/workflows/pr-icon-update.yml

This PR introduces essential improvements to the GitHub action responsible for creating PRs when icons are updated. It includes a well-defined title, description, and sets up reviewers for a more organized and efficient process.

chore(icons): add proper title, desc and reviewers

---

.github/workflows/pr-icon-update.yml

ci(icons): fix yaml syntax

---

.github/workflows/pr-icon-update.yml

This PR tries to escape colon in YAML.

ci(icons): fix PR title

---

.github/workflows/pr-icon-update.yml

This PR addresses a fix for the PR title related to icon updates.

ci(icons): fix PR title 2

---

package-lock.json
packages/components/checkbox/src/Checkbox.doc.mdx
packages/components/checkbox/src/Checkbox.stories.tsx
packages/components/input/src/Input.doc.mdx
packages/components/radio-group/src/RadioGroup.doc.mdx
packages/components/radio-group/src/RadioGroup.stories.tsx
packages/components/switch/src/Switch.doc.mdx
packages/components/textarea/src/Textarea.doc.mdx

docs: fixed invalid reference to a formfield prop in multiple components

---

packages/components/drawer/src/DrawerBody.tsx
packages/components/drawer/src/DrawerFooter.tsx
packages/components/drawer/src/DrawerHeader.tsx

fix(drawer): classNames order

---

packages/components/button/src/Button.styles.tsx
packages/components/checkbox/src/CheckboxInput.styles.ts
packages/components/chip/src/Chip.styles.tsx
packages/components/chip/src/ChipClearButton.styles.tsx
packages/components/dialog/src/DialogBody.tsx
packages/components/dialog/src/DialogContent.styles.tsx
packages/components/drawer/src/DrawerBody.tsx
packages/components/popover/src/PopoverContent.styles.ts
packages/components/radio-group/src/RadioInput.styles.ts
packages/components/switch/src/SwitchInput.styles.ts
packages/components/tabs/src/TabsContent.styles.ts
packages/components/tabs/src/TabsList.styles.ts
packages/components/tabs/src/TabsTrigger.styles.ts
packages/components/tag/src/Tag.styles.tsx
packages/utils/tailwind-plugins/utilities/index.js

**TASK**: #1437
Apply new focus styles on our components to see how it looks, because our current focus styles can be hard to spot depending on the background.

feat: update focus styles of components

---

packages/components/tabs/src/useResizeObserver.ts

Fix a bug view on [Sentry](https://lbc-france-lj.sentry.io/issues/4458703337/events/1f9f0dc4fe994bf8befb3723f29b1c5b/?environment=production&project=5270450&query=is%3Aunresolved&referrer=next-event&statsPeriod=24h&stream_index=1)

fix(tabs): optional chaining on array access

---

documentation/contributing/Contributors.mdx
documentation/contributing/Maintainers.mdx
vite.config.ts

docs: add maintainers and contributors documented

---

package-lock.json
packages/components/text-link/.npmignore
packages/components/text-link/package.json
packages/components/text-link/src/TextLink.doc.mdx
packages/components/text-link/src/TextLink.stories.tsx
packages/components/text-link/src/TextLink.test.tsx
packages/components/text-link/src/TextLink.tsx
packages/components/text-link/src/index.ts
packages/components/text-link/tsconfig.json
packages/components/text-link/vite.config.ts

**TASK**: #1440 
Providing an experimental version to discuss specs with designers and iterate on once the specs are final.

feat(text-link): text-link package (experimental)

---

.github/workflows/pr-icon-update.yml

This PR ensures proper escaping of colon in PR title for YAML GitHub Action about icon updates.

ci(icons): escaping colon in pr title

---

.storybook/manager.js
.storybook/theme/getTheme.js
documentation/helpers/ArgTypes/index.tsx
documentation/helpers/ToC/index.tsx

style: theaming sb

---

packages/components/dialog/src/Dialog.stories.tsx

fix(dialog): release stable dialog

---

package-lock.json
package.json
vitest.setup.ts

Revert "test: vitest update"

---

.github/workflows/release.yml

https://github.com/akhilmhdh/contributors-readme-action/blob/master/README.md#optional-parameters

fix: collaborators

---

packages/components/chip/src/useChipElement.tsx

refactor(chip): add missed component to the hook

---

packages/components/text-link/package.json
packages/components/text-link/src/TextLink.stories.tsx

**TASK**: #1529 
Release `TextLink` as stable.

fix(text-link): release stable text-link

---

packages/components/progress/src/Progress.doc.mdx
packages/components/progress/src/Progress.stories.tsx
packages/components/progress/src/Progress.tsx
packages/components/progress/src/ProgressBar.styles.ts
packages/components/progress/src/ProgressBar.tsx
packages/components/progress/src/ProgressContext.tsx
packages/components/progress/src/ProgressIndicator.styles.ts
packages/components/progress/src/ProgressIndicator.tsx

**TASK**: #1539 
This PR adds shape prop to `Progress` component

1539 component progress update default border radius

---

packages/components/progress/src/Progress.doc.mdx
packages/components/progress/src/Progress.stories.tsx
packages/components/progress/src/Progress.tsx
packages/components/progress/src/ProgressBar.styles.ts
packages/components/progress/src/ProgressBar.tsx
packages/components/progress/src/ProgressContext.tsx
packages/components/progress/src/ProgressIndicator.styles.ts
packages/components/progress/src/ProgressIndicator.tsx
packages/components/progress/src/index.ts

**TASK**: #1538 
This PR adds intent prop support to the `Progress` component

feat(progress): add intent prop

---

.github/workflows/pr-icon-update.yml

This pull request updates the PR titles when icons undergo changes. This adjustment ensures that versioning functions seamlessly. Kudos to @andresin87 for his valuable contribution!

ci(icons): adjust PR title for icon updates

---

packages/components/slider/src/Slider.doc.mdx
packages/components/slider/src/Slider.stories.tsx

docs(slider): add "restricted values" section

---

packages/components/rating/src/Rating.stories.tsx
packages/components/rating/src/Rating.test.tsx
packages/components/rating/src/Rating.tsx
packages/components/rating/src/RatingStar.styles.ts
packages/components/rating/src/RatingStar.tsx
packages/components/rating/src/index.ts
packages/components/rating/src/types.ts
packages/components/rating/src/utils.test.ts
packages/components/rating/src/utils.ts

feat(rating): Rating component API proposal

---

package-lock.json
packages/components/select/.npmignore
packages/components/select/LICENSE.md
packages/components/select/README.md
packages/components/select/package.json
packages/components/select/src/Select.doc.mdx
packages/components/select/src/Select.stories.tsx
packages/components/select/src/Select.test.tsx
packages/components/select/src/Select.tsx
packages/components/select/src/index.ts
packages/components/select/tsconfig.json
packages/components/select/vite.config.ts

Bootstrapping `@spark-ui/select` package (code will come in future PRs, this one is to avoid too many changes at once and facilitate review)

feat(select): bootstrap select package

---

package-lock.json
packages/components/rating/src/Rating.doc.mdx
packages/components/rating/src/Rating.stories.tsx
packages/components/rating/src/Rating.tsx

**TASK**: #1577 
Following [API proposal](https://github.com/adevinta/spark/pull/1605), we now want to complete documentation on Rating component.

docs(rating): component rating docs

---

packages/components/rating/src/Rating.tsx
packages/components/rating/src/utils.test.ts
packages/components/rating/src/utils.ts

**TASK**: #1577 
Regarding @andresin87 and @Powerplex remarks, we may want to update the Rating input value, for accessibility reasons.

feat(rating): upd rating input step

---

packages/components/rating/src/Rating.stories.tsx

Updating sizes on documentation to be consistent with design guidelines.

docs(rating): upd sizing to comply design guidelines

---

packages/components/alert-dialog/package.json

**TASK**: None
This PR will release the first version of the `AlertDialog`

feat(alert-dialog): release first version

---

package-lock.json
packages/components/select/package.json
packages/components/select/src/Select.stories.tsx
packages/components/select/src/Select.test.tsx
packages/components/select/src/Select.tsx
packages/components/select/src/SelectContext.tsx
packages/components/select/src/SelectItem.tsx
packages/components/select/src/SelectItems.tsx
packages/components/select/src/SelectItemsGroup.tsx
packages/components/select/src/SelectLeadingIcon.tsx
packages/components/select/src/SelectTrigger.tsx
packages/components/select/src/SelectValue.tsx
packages/components/select/src/index.ts
packages/components/select/src/utils.ts

Draft for discussing Select vs Dropdown vs Combobox API and requirements.

Select component - first pass

---

package-lock.json
packages/components/combobox/.npmignore
packages/components/combobox/LICENSE.md
packages/components/combobox/README.md
packages/components/combobox/package.json
packages/components/combobox/src/Combobox.doc.mdx
packages/components/combobox/src/Combobox.stories.tsx
packages/components/combobox/src/Combobox.test.tsx
packages/components/combobox/src/Combobox.tsx
packages/components/combobox/src/index.ts
packages/components/combobox/tsconfig.json
packages/components/combobox/vite.config.ts

Bootstrap of `@spark-ui/combobox` package.

feat(combobox): bootstrap combobox package

---

package-lock.json
packages/components/dropdown/src/Dropdown.stories.tsx
packages/components/dropdown/src/Dropdown.tsx
packages/components/dropdown/src/DropdownContext.tsx
packages/components/dropdown/src/DropdownItem.tsx
packages/components/dropdown/src/DropdownItems.tsx
packages/components/dropdown/src/DropdownPopover.tsx
packages/components/dropdown/src/DropdownTrigger.tsx
packages/components/dropdown/src/index.ts

**TASK**: 
sol`I`d: Interface segregation principle: A client should never be forced to implement an interface that it doesn't use, or clients shouldn't be forced to depend on methods they do not use.
The Popover where the items are placed when the dropdown is opened is segregated from the ItemsList in order to place the itemsList within the popover or do not and create your own stuff.

feat(dropdown): add DropDown.Popover

---

packages/components/dropdown/src/Dropdown.stories.tsx
packages/components/dropdown/src/Dropdown.test.tsx
packages/components/dropdown/src/DropdownContext.tsx
packages/components/dropdown/src/DropdownItems.tsx
packages/components/dropdown/src/DropdownPopover.tsx
packages/components/dropdown/src/DropdownTrigger.tsx
packages/components/dropdown/src/DropdownValue.tsx
packages/components/dropdown/src/index.ts

**TASK**: #1680 
Inspired from Radix: https://www.radix-ui.com/primitives/docs/components/select#value
- `Dropdown.Value` accepts a placeholder (string) for when no item is selected.
- You can use `children` to customize what is shown when an item is selected.
- By default, will display the selected item's text.

feat(dropdown): dropdown value component inside trigger

---

package-lock.json
packages/components/progress-tracker/.npmignore
packages/components/progress-tracker/LICENSE.md
packages/components/progress-tracker/README.md
packages/components/progress-tracker/package.json
packages/components/progress-tracker/src/ProgressTracker.doc.mdx
packages/components/progress-tracker/src/ProgressTracker.stories.tsx
packages/components/progress-tracker/src/ProgressTracker.test.tsx
packages/components/progress-tracker/src/ProgressTracker.tsx
packages/components/progress-tracker/src/index.ts
packages/components/progress-tracker/tsconfig.json
packages/components/progress-tracker/vite.config.ts

Scaffolding of the progress tracker component

feat(progress-tracker): init progress tracker

---

package-lock.json
packages/components/dropdown/package.json
packages/components/dropdown/src/Dropdown.doc.mdx
packages/components/dropdown/src/Dropdown.stories.tsx
packages/components/dropdown/src/Dropdown.test.tsx
packages/components/dropdown/src/DropdownContext.tsx
packages/components/dropdown/src/DropdownItem.tsx
packages/components/dropdown/src/DropdownItems.tsx
packages/components/dropdown/src/DropdownPopover.tsx
packages/components/dropdown/src/DropdownTrigger.tsx

**TASK**: #1697
- Check task for description
- I had to split the "big story" we had in multiple stories to make sure label linking was working in every configuration, I updated the existing unit test to check that the `Dropdown.Trigger` and `Dropdown.Items` are properly linked with an accessible name.
- `downshift` is managing all the `id, for, htmlFor, ariaLabelledBy` attributes.

feat(dropdown): dropdown label management

---

package-lock.json
packages/components/dropdown/package.json
packages/components/dropdown/src/Dropdown.doc.mdx
packages/components/dropdown/src/Dropdown.stories.tsx
packages/components/dropdown/src/DropdownLeadingIcon.tsx
packages/components/dropdown/src/DropdownTrigger.tsx
packages/components/dropdown/src/index.ts
packages/components/dropdown/src/utils.ts

feat(dropdown): add leadingIcon

---

package-lock.json
packages/components/dropdown/package.json
packages/components/dropdown/src/Dropdown.stories.tsx
packages/components/dropdown/src/Dropdown.test.tsx
packages/components/dropdown/src/DropdownItem.tsx
packages/components/dropdown/src/DropdownItems.tsx
packages/components/dropdown/src/DropdownLeadingIcon.tsx
packages/components/dropdown/src/DropdownPopover.tsx
packages/components/dropdown/src/DropdownTrigger.tsx
packages/components/dropdown/src/DropdownValue.tsx

Dropdown styles figma sync

---

package-lock.json
package.json

feat: bump TCV to 1.10.0

---

package-lock.json
package.json
packages/utils/tailwind-plugins/sizings/index.js

feat(tailwind-plugins): add size field to sizing plugin

---

packages/components/progress-tracker/src/ProgressTracker.doc.mdx
packages/components/progress-tracker/src/ProgressTracker.stories.tsx
packages/components/progress-tracker/src/ProgressTracker.tsx
packages/components/progress-tracker/src/ProgressTrackerContext.ts
packages/components/progress-tracker/src/ProgressTrackerStep.styles.ts
packages/components/progress-tracker/src/ProgressTrackerStep.tsx
packages/components/progress-tracker/src/ProgressTrackerStepIndicator.styles.ts
packages/components/progress-tracker/src/ProgressTrackerStepIndicator.tsx
packages/components/progress-tracker/src/ProgressTrackerStepLabel.styles.ts
packages/components/progress-tracker/src/stepIndicatorVariants/index.ts
packages/components/progress-tracker/src/stepIndicatorVariants/outline.ts
packages/components/progress-tracker/src/stepIndicatorVariants/tinted.ts

**TASK**: #1581 
Adds additionnal features such as design and intent prop.

feat(progress-tracker): extends progress-tracker feat.

---

.gitignore
package-lock.json
packages/components/select/src/Select.stories.tsx
packages/components/select/src/SelectContext.tsx
packages/components/select/src/SelectItems.tsx

feat(select): formfield name and "required"

---

package-lock.json
packages/components/select/src/SelectTrigger.styles.tsx

Forgot to apply focus style on fake trigger of the Select package.

feat(select): select focus styles

---

packages/components/dropdown/src/DropdownItem.tsx

Apply proper cursor on Dropdown.Item depending if its disabled or not.

fix(dropdown): apply proper cursor on dropdown items

---

packages/components/progress-tracker/src/ProgressTracker.doc.mdx
packages/components/progress-tracker/src/ProgressTracker.stories.tsx
packages/components/progress-tracker/src/ProgressTracker.tsx
packages/components/progress-tracker/src/ProgressTrackerContext.ts
packages/components/progress-tracker/src/ProgressTrackerStep.tsx
packages/components/progress-tracker/src/ProgressTrackerStepIndicator.tsx
packages/components/progress-tracker/src/index.ts

**TASK**: #1581 
As we agreed not to bring any kind of logic within our UI components, we remove here previous implementation of step interaction.

feat(progress-tracker): updates step interactivity

---

package-lock.json
packages/components/progress-tracker/package.json
packages/components/progress-tracker/src/ProgressTracker.stories.tsx

**TASK**: #1581 
Publication of the component after validation.

chore(progress-tracker): publish progress-tracker

---

package-lock.json
package.json
tailwind.config.viewer.cjs

bump TCV to 2.0.0, which includes support for multiple themes

feat: bump TCV to 2.0.0

---

packages/components/slider/src/SliderThumb.styles.ts

**TASK**: #1816 
Following design team decision, we want to change interactivity styles, for readability.

style(slider): upd interactivity styles

---

package-lock.json
packages/components/select/src/SelectItems.tsx

Forgot ref forwarding on `Select.Items` (html `select` tag)

fix(select): forward ref to select items

---

packages/components/select/src/SelectTrigger.styles.tsx

fix(select): fix text-size defined

---

package-lock.json
packages/components/link-box/.npmignore
packages/components/link-box/LICENSE.md
packages/components/link-box/README.md
packages/components/link-box/package.json
packages/components/link-box/src/LinkBox.doc.mdx
packages/components/link-box/src/LinkBox.stories.tsx
packages/components/link-box/src/LinkBox.test.tsx
packages/components/link-box/src/LinkBox.tsx
packages/components/link-box/src/LinkOverlay.tsx
packages/components/link-box/src/index.ts
packages/components/link-box/tsconfig.json
packages/components/link-box/vite.config.ts

**TASK**: None
This PR adds `LinkBox` component based on the [ChakraUI](https://chakra-ui.com/docs/components/link-overlay/usage#) one

feat(link-box): add first iteration

---

package-lock.json
packages/components/snackbar/.npmignore
packages/components/snackbar/LICENSE.md
packages/components/snackbar/README.md
packages/components/snackbar/package.json
packages/components/snackbar/src/Snackbar.doc.mdx
packages/components/snackbar/src/Snackbar.stories.tsx
packages/components/snackbar/src/Snackbar.test.tsx
packages/components/snackbar/src/Snackbar.tsx
packages/components/snackbar/src/index.ts
packages/components/snackbar/tsconfig.json
packages/components/snackbar/vite.config.ts

**TASK**: #1893
Init Snackbar.

feat(snackbar): init package

---

bin/check-a11y.js
package-lock.json
package.json

After last update, Selenium Webdriver package seemed to have changed some options on headless mode (see [here](https://github.com/SeleniumHQ/selenium/commit/5a97adf9864a346fdd8914cdb1b601c05dd837ac#diff-d162e4f4aff030903cf7abba451d452a98851836091b22941f38d6174fc086ef)). Also recently Firefox implementation seemed to have been broken, so we switch to Chrome (see [here](https://github.com/SeleniumHQ/selenium/issues/13169) and [there](https://github.com/SeleniumHQ/selenium/issues/13252)).

fix: fix a11y check task (selenium firefox issue)

---

packages/components/badge/src/BadgeItem.styles.tsx

**TASK**: #1906
Badge outline should utilize the "surface" token

fix(badge): badge outline now utilizes "surface" token

---

package-lock.json
packages/components/dropdown/package.json

**TASK**: #1918 
Update Downshift to version 8.3.2 to resolve [issue](https://github.com/downshift-js/downshift/issues/1447) of callbacks triggering twice during the `onChange` event when **multiple** prop is true

fix(dropdown): update to downshift 8.3.2

---

packages/components/button/src/Button.tsx

**TASK**: #1928 
See attached issue

fix(button): prevent unwanted form submissions from buttons

---

.github/workflows/quality.yml

**TASK**: 
Codecov might not block de CI (just warn)
https://github.com/codecov/codecov-action

ci: non-blocking codecov error

---

documentation/helpers/ArgTypes/index.tsx
packages/components/snackbar/src/Snackbar.doc.mdx
packages/components/snackbar/src/Snackbar.stories.tsx
packages/components/snackbar/src/Snackbar.styles.ts
packages/components/snackbar/src/Snackbar.test.tsx
packages/components/snackbar/src/Snackbar.tsx
packages/components/snackbar/src/SnackbarItem.styles.ts
packages/components/snackbar/src/SnackbarItem.tsx
packages/components/snackbar/src/index.ts
packages/components/snackbar/src/snackbarVariants.ts

**TASK**: #1893
In this PR we add basic styles for the snackbar item, with animations and positionning.

feat(snackbar): add snackbar basic styles

---

documentation/helpers/ArgTypes/index.tsx
package-lock.json
packages/components/snackbar/package.json
packages/components/snackbar/src/Snackbar.doc.mdx
packages/components/snackbar/src/Snackbar.stories.tsx
packages/components/snackbar/src/Snackbar.tsx
packages/components/snackbar/src/SnackbarItem.styles.ts
packages/components/snackbar/src/SnackbarItem.tsx

**TASK**: #1893 
As we provide both component and function here, we want to adapt documentation format.

docs(snackbar): update snackbar docs

---

packages/components/chip/src/Chip.tsx
packages/components/chip/src/index.ts

Currently, we have a [dependabot PR](https://github.com/adevinta/spark/pull/1944) that throws a TS error. The aim of this PR is to fix that error, allowing us to merge the dependabot PR.

fix(chip): update TS related things for forthcoming @react/types update

---

package-lock.json
packages/components/combobox/src/Combobox.stories.tsx
packages/components/combobox/src/ComboboxClearButton.tsx
packages/components/combobox/src/ComboboxContext.tsx
packages/components/combobox/src/ComboboxDisclosure.tsx
packages/components/combobox/src/ComboboxDivider.tsx
packages/components/combobox/src/ComboboxEmpty.tsx
packages/components/combobox/src/ComboboxGroup.tsx
packages/components/combobox/src/ComboboxInput.tsx
packages/components/combobox/src/ComboboxItem.tsx
packages/components/combobox/src/ComboboxItemContext.tsx
packages/components/combobox/src/ComboboxItems.tsx
packages/components/combobox/src/ComboboxItemsGroupContext.tsx
packages/components/combobox/src/ComboboxLabel.tsx
packages/components/combobox/src/ComboboxLeadingIcon.tsx
packages/components/combobox/src/ComboboxPopover.tsx
packages/components/combobox/src/ComboboxSelectedItems.tsx
packages/components/combobox/src/ComboboxTrigger.styles.tsx
packages/components/combobox/src/ComboboxTrigger.tsx
packages/components/combobox/src/index.ts
packages/components/combobox/src/tests/Combobox.test.tsx
packages/components/combobox/src/tests/multipleSelection.test.tsx
packages/components/combobox/src/tests/singleSelection.test.tsx
packages/components/combobox/src/tests/test-utils.ts
packages/components/combobox/src/useCombobox/multipleSelectionReducer.ts
packages/components/combobox/src/useCombobox/singleSelectionReducer.ts
packages/components/combobox/src/utils.ts

- Logic that we build together with @andresin87 on a separate PoC is moved back into Spark
- Mainly, it adds chips (selected items) for multiple selection behaviour
- Improves blur behaviour
- Improves focus logic of open/close.

refactor(combobox): sync combobox logic to aria pattern

---

packages/components/divider/package.json
packages/components/divider/src/Divider.stories.tsx

**TASK**: 
release divider
followed the same strategy as https://github.com/adevinta/spark/pull/1873

release(divider): stable v1

---

packages/components/combobox/src/Combobox.doc.mdx
packages/components/combobox/src/Combobox.stories.tsx
packages/components/combobox/src/ComboboxDisclosure.tsx
packages/components/combobox/src/ComboboxInput.tsx
packages/components/combobox/src/ComboboxSelectedItems.tsx
packages/components/combobox/src/ComboboxTrigger.styles.tsx
packages/components/combobox/src/ComboboxTrigger.tsx

feat(combobox): add readOnly and disabled state

---

package-lock.json
packages/components/combobox/src/Combobox.doc.mdx
packages/components/combobox/src/Combobox.stories.tsx
packages/components/combobox/src/ComboboxContext.tsx
packages/components/combobox/src/ComboboxInput.tsx
packages/components/combobox/src/ComboboxSelectedItems.tsx

**TASK**: #1964 
- `value` and `onValueChange` to control input value

feat(combobox): combobox input controlled behaviour

---

package-lock.json
packages/components/combobox/src/Combobox.doc.mdx
packages/components/dropdown/src/Dropdown.doc.mdx
packages/components/select/src/Select.doc.mdx

- added a11y section to combobox doc
- added component role description to combobox doc

docs(combobox): added a11y section and description to combobox

---

packages/components/dropdown/src/Dropdown.doc.mdx
packages/components/dropdown/src/DropdownItems.tsx
packages/components/dropdown/src/DropdownPopover.tsx
packages/components/dropdown/src/useDropdown.ts

fix(combobox): content stacking display and positioning issues

---

packages/components/combobox/src/ComboboxItems.tsx

fix(combobox): invalid log

---

package-lock.json
packages/components/combobox/src/Combobox.stories.tsx
packages/components/combobox/src/ComboboxContext.tsx
packages/components/combobox/src/ComboboxItems.tsx
packages/components/combobox/src/ComboboxPopover.tsx
packages/components/dropdown/src/DropdownPopover.tsx

- scroll into view combobox items when they are highlighed (keyboard)

fix(combobox): scroll combobox items into view

---

packages/components/combobox/src/ComboboxItems.tsx

refactor(combobox): isLoading spinner centered

---

packages/components/snackbar/src/SnackbarItemAction.tsx
packages/components/snackbar/src/SnackbarItemClose.tsx
packages/components/snackbar/src/SnackbarItemIcon.tsx

fix(snackbar): prevent snackbar components to flex (appart main content)

---

packages/components/combobox/src/ComboboxItems.tsx
packages/components/dropdown/src/DropdownItems.tsx

fix(dropdown): apply pointer-event styles correctly when dropdown is open

---

package-lock.json
packages/components/snackbar/package.json
packages/components/snackbar/src/Snackbar.test.tsx
packages/components/snackbar/src/SnackbarItem.styles.ts
packages/components/snackbar/src/SnackbarItem.tsx
packages/components/snackbar/src/SnackbarRegion.styles.ts
packages/components/snackbar/src/useSwipe.test.ts
packages/components/snackbar/src/useSwipe.ts
packages/utils/tailwind-plugins/animations/index.js

**TASK**: #1893 
We want to support swipe gesture on our component. For now, we only want the Snackbar to be closed on left/right gestures.

feat(snackbar): add swipe gesture to snackbar

---

packages/components/dropdown/src/Dropdown.stories.tsx

This PR adds stories that are not displayed in the sidebar or documentation, but are accessible via direct URL.
This feature is particularly useful for QA purposes, as it allows specific scenarios to be tested without cluttering the main storybook interface.

docs(dropdown): introduce specific stories dedicated for QA

---

.github/workflows/quality.yml
.gitignore
.storybook/preview.jsx
bin/check-a11y.js
documentation/helpers/A11yReport/index.tsx
package.json
public/a11y-report.json

**TASK**: #2034 
In order to prepare data for Spark metrics dashboard, we want to refacto the actual a11y script.

refactor: refacto a11y check to prepare JSON export

---

package-lock.json
packages/components/snackbar/package.json

Related to #2092 . Some deps weren't declared properly, so we want to fix this in the component.

chore(snackbar): improve deps declaration for sackbar

---

packages/components/combobox/src/ComboboxInput.tsx

##f ix(combobox): input background color for dark mode
**TASK**:

fix(combobox): input background color for dark mode

---

packages/components/combobox/src/ComboboxClearButton.tsx

fix(combobox): replace clear button from fill to outline

---

packages/components/input/src/InputClearButton.tsx

**TASK**: 
related to https://github.com/adevinta/spark/pull/2103

fix(input): replace from fill to outline clear button

---

packages/components/combobox/src/ComboboxSelectedItems.tsx

fix(combobox): multi select disabled hoverable

---

package-lock.json

chore: reconcile ci

---

.github/composite-actions/install/action.yml
.github/workflows/manual-deploy.yml
.github/workflows/mirror.yml
.github/workflows/pr-icon-update.yml
.github/workflows/quality.yml
.github/workflows/release.yml

chore: update checkout action

---

packages/components/combobox/src/Combobox.doc.mdx

Debugging npm release process by updating doc of one package.

docs(combobox): update doc to test npm release of combobox

---

package-lock.json
packages/components/input/src/Input.doc.mdx
packages/components/snackbar/src/Snackbar.doc.mdx
packages/components/textarea/src/Textarea.doc.mdx
packages/utils/tailwind-plugins/index.js

Following the issue with expired NPM token, I updated the package that were not published to sync them on npm.

chore: changes in unpublished packages to rerelease them

---

packages/components/form-field/src/FormField.doc.mdx

Forcing npm release of `FormField`

fix(form-field): latest version of form-field was not published to npm

---

packages/components/icons/src/index.doc.mdx

Followind npm issue, we need to publish a new version of icons and sync it with dependant packages.

docs(icons): sync icons with npm

---

package-lock.json
packages/components/dropdown/src/DropdownPopover.tsx
packages/components/popover/src/PopoverContent.styles.ts
packages/components/popover/src/PopoverContent.tsx

**TASK**: #2158 
Check ticket description.

feat(popover): added control over popover elevation

---

package-lock.json
packages/utils/cli/package.json

fix(internal-utils): missed dependency

---

packages/utils/cli/package.json

fix(cli-utils): fix binary file indicator

---

package-lock.json
packages/utils/cli/src/scan/index.mjs

fix(cli-utils): improve log messages

---

packages/components/popover/src/Popover.doc.mdx
packages/components/popover/src/Popover.stories.tsx
packages/components/popover/src/Popover.tsx
packages/components/popover/src/PopoverArrow.tsx
packages/components/popover/src/PopoverContent.styles.ts
packages/components/popover/src/PopoverContent.tsx
packages/components/popover/src/PopoverContext.tsx

**TASK**: #2163 
Implementing `intent` prop on Popover (colors)
https://github.com/adevinta/spark/assets/2033710/96001107-e100-4fc6-b5e3-a5a97f1660aa

feat(popover): added intents to popover

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/release.yml
packages/utils/cli/README.md
packages/utils/cli/src/generate/templates/component/[README.md].js

Fixing broken linkgs following GH tags updates.

chore: adapted gh links to match new labels

---

package-lock.json
packages/components/collapsible/.npmignore
packages/components/collapsible/LICENSE.md
packages/components/collapsible/README.md
packages/components/collapsible/package.json
packages/components/collapsible/src/Collapsible.doc.mdx
packages/components/collapsible/src/Collapsible.stories.tsx
packages/components/collapsible/src/Collapsible.test.tsx
packages/components/collapsible/src/Collapsible.tsx
packages/components/collapsible/src/CollapsibleContent.tsx
packages/components/collapsible/src/CollapsibleTrigger.tsx
packages/components/collapsible/src/index.ts
packages/components/collapsible/tsconfig.json
packages/components/collapsible/vite.config.ts

**TASK**: #2177 
`Collapsible` component (pattern). Based on https://zagjs.com/components/react/collapsible.
Follows Disclosure ARIA pattern: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/

feat(collapsible): collapsible package, using zagjs

---

packages/components/collapsible/src/Collapsible.doc.mdx
packages/components/collapsible/src/CollapsibleTrigger.tsx

Adding custom `ArgTypes` (props table) to `Collapsible` compound in Storybook.

docs(combobox): added collapsibles compound props to sb

---

package-lock.json
packages/components/collapsible/package.json
packages/components/collapsible/src/Collapsible.doc.mdx
packages/components/collapsible/src/Collapsible.stories.tsx
packages/components/collapsible/src/Collapsible.tsx
packages/components/collapsible/src/CollapsibleContent.tsx
packages/components/collapsible/src/CollapsibleTrigger.tsx
packages/utils/tailwind-plugins/animations/index.js

**TASK**: #2224 
See attached ticket. Adding `Collapsible` animation using both opacity and height animation.

style(collapsible): collapsible animation

---

package-lock.json
packages/components/accordion/.npmignore
packages/components/accordion/LICENSE.md
packages/components/accordion/README.md
packages/components/accordion/package.json
packages/components/accordion/src/Accordion.doc.mdx
packages/components/accordion/src/Accordion.stories.tsx
packages/components/accordion/src/Accordion.test.tsx
packages/components/accordion/src/Accordion.tsx
packages/components/accordion/src/AccordionItem.tsx
packages/components/accordion/src/AccordionItemContent.tsx
packages/components/accordion/src/AccordionItemContext.tsx
packages/components/accordion/src/AccordionItemTrigger.tsx
packages/components/accordion/src/index.ts
packages/components/accordion/tsconfig.json
packages/components/accordion/vite.config.ts
packages/utils/cli/src/generate/templates/component/[package.json].js

Experimental `Accordion` component, based on [Zagjs](https://zagjs.com/components/react/accordion).
https://github.com/adevinta/spark/assets/2033710/f4ec5c28-d092-4795-b343-28f9f08a4d57

feat(accordion): accordion component

---

packages/components/collapsible/src/Collapsible.tsx

feat(collapsible): add "ids" props, useful for composition

---

package-lock.json
packages/components/snackbar/src/Snackbar.stories.tsx
packages/components/snackbar/src/Snackbar.tsx
packages/components/snackbar/src/SnackbarItem.styles.ts
packages/components/snackbar/src/SnackbarItem.tsx
packages/components/snackbar/src/useSwipe.ts

**TASK**: #2199 
Snackbar animations (with `translate` property) were having edge case issue with collission between different data attributes bringing their own translate rule.

fix(snackbar): fixes and improves snackbar swipe styles to avoid translate collision

---

packages/components/accordion/src/Accordion.doc.mdx
packages/components/accordion/src/Accordion.stories.tsx
packages/components/accordion/src/Accordion.tsx
packages/components/accordion/src/AccordionItem.tsx

- added `design` prop (`outlined | filled`)

feat(accordion): outlined and filled designs

---

packages/components/accordion/src/Accordion.tsx
packages/components/accordion/src/AccordionItemTrigger.tsx

Updating `Accordion.ItemTrigger` min height to `48px`.
Fixed typo in doc.

fix(accordion): updated accordion header height

---

package-lock.json
packages/components/accordion/package.json
packages/components/accordion/src/Accordion.stories.tsx

fix(accordion): accordion stable release

---

packages/components/popover/src/PopoverCloseButton.tsx
packages/components/popover/src/PopoverContent.styles.ts
packages/components/popover/src/PopoverContent.tsx
packages/components/popover/src/PopoverContext.tsx

feat(popover): use css "has" selector rather than JS to apply specific styles

---

packages/components/tag/src/Tag.tsx

feat(tag): expose ValidTagDesignIntent type

---

package-lock.json
package.json
tailwind.config.viewer.mjs

feat: bump TCV to 3.0.0 (ESM support)

---

lerna.json
package.json
packages/utils/theme/README.md
packages/utils/theme/src/index.doc.mdx

Spark versioning (Lerna) goes from `independant` to `fixed`.

chore(theme-utils): test lerna fixed versioning

---

e2e/combobox-within-dialog/index.spec.tsx
e2e/dropdown-with-adjacent-buttons/index.spec.tsx
e2e/dropdown-within-dialog/index.spec.tsx

https://x.com/housecor/status/1816867564796117228

refactor: split tests into multiple steps

---

package-lock.json
packages/components/accordion/package.json
packages/components/badge/package.json
packages/components/button/package.json
packages/components/checkbox/package.json
packages/components/chip/package.json
packages/components/collapsible/package.json
packages/components/dialog/package.json
packages/components/drawer/package.json
packages/components/form-field/package.json
packages/components/icon-button/package.json
packages/components/icon/package.json
packages/components/input/package.json
packages/components/kbd/package.json
packages/components/label/package.json
packages/components/popover/package.json
packages/components/portal/package.json
packages/components/progress-tracker/package.json
packages/components/progress/package.json
packages/components/radio-group/package.json
packages/components/slider/package.json
packages/components/snackbar/package.json
packages/components/spinner/package.json
packages/components/switch/package.json
packages/components/tabs/package.json
packages/components/textarea/package.json
packages/utils/cli/src/generate/templates/component/[package.json].js

Update the handling of Spark packages (Tailwind related) in the `package.json` of our components.
Currently, these packages are inconsistently listed in the `peerDependencies` and are not marked with the latest version but an outdated one. To address this, we will mark the version as `latest` to ensure it is always up to date.

chore: update handling of Spark/Tailwind dependencies

---

package-lock.json
package.json

Dependency bump.
`"eslint-plugin-react": "7.35.0",`

chore: bump eslint-plugin-react to 7.35.0

---

e2e/a11y/pages/Accordion.tsx
e2e/a11y/pages/AlertDialog.tsx
e2e/a11y/pages/Badge.tsx
e2e/a11y/pages/Checkbox.tsx
e2e/a11y/pages/Collapsible.tsx
e2e/a11y/routes/components.ts
e2e/a11y/routes/elements.tsx
public/a11y/a11y-report.json

**TASK**: #2341 
Adding some tests to our PW+Axe setup. As there would be a lot of added files, there will be several nested PRs :+1:

test: adds accessibility implementations for PW testing

---

package-lock.json
packages/components/accordion/package.json
packages/components/collapsible/package.json

Bump `zag-js` dependencies across packages.

chore(collapsible): bump zagjs dependencies

---

e2e/a11y/pages/AlertDialog.tsx
e2e/a11y/pages/Combobox.tsx
e2e/a11y/pages/Divider.tsx
e2e/a11y/pages/Drawer.tsx
e2e/a11y/pages/Dropdown.tsx
e2e/a11y/pages/FormField.tsx
e2e/a11y/pages/IconButton.tsx
e2e/a11y/routes/components.ts
e2e/a11y/routes/elements.tsx
public/a11y/a11y-report.json

**TASK**: #2351 
Adds more implementations to test accessibility with PW+Axe workflow :muscle:

test: adds more implementations for pw+axe testing

---

package-lock.json
packages/components/pagination/.npmignore
packages/components/pagination/LICENSE.md
packages/components/pagination/README.md
packages/components/pagination/package.json
packages/components/pagination/src/Pagination.doc.mdx
packages/components/pagination/src/Pagination.stories.tsx
packages/components/pagination/src/Pagination.test.tsx
packages/components/pagination/src/Pagination.tsx
packages/components/pagination/src/PaginationContext.tsx
packages/components/pagination/src/PaginationEllipsis.tsx
packages/components/pagination/src/PaginationFirstPageTrigger.tsx
packages/components/pagination/src/PaginationItem.tsx
packages/components/pagination/src/PaginationLastPageTrigger.tsx
packages/components/pagination/src/PaginationNextTrigger.tsx
packages/components/pagination/src/PaginationPages.tsx
packages/components/pagination/src/PaginationPrevTrigger.tsx
packages/components/pagination/src/index.ts
packages/components/pagination/src/utils.ts
packages/components/pagination/tsconfig.json
packages/components/pagination/vite.config.ts

`Pagination` component proposal based on `ZagJS` API.

fix(pagination): new pagination component

---

package-lock.json
packages/components/stepper/package.json
packages/components/stepper/src/Stepper.doc.mdx
packages/components/stepper/src/Stepper.stories.tsx
packages/components/stepper/src/Stepper.test.tsx
packages/components/stepper/src/Stepper.tsx
packages/components/stepper/src/StepperButton.tsx
packages/components/stepper/src/StepperInput.tsx
packages/components/stepper/src/index.ts
packages/components/stepper/src/types.ts
packages/components/stepper/src/useStepper.ts

**TASK**: https://jira.ets.mpi-internal.com/browse/SPA-48
Initialize component with basic behavior.

feat(stepper): setting up stepper component with basic behavior

---

packages/components/pagination/src/Pagination.test.tsx

Covered `FirstPageTrigger` and `LastPageTrigger` in pagination tests.

test(pagination): improved pagination coverage

---

package-lock.json
packages/components/chip/src/Chip.doc.mdx
packages/components/chip/src/Chip.stories.tsx
packages/components/chip/src/Chip.styles.tsx

**TASK**: [SPA-5](https://jira.ets.mpi-internal.com/browse/SPA-5)
- Removed hard-coded max-width from `Chip`
- Removed or simplified `Chip`'s stories.

feat(chip): chips no longer have max width

---

e2e/a11y/pages/Pagination.tsx
e2e/a11y/pages/Popover.tsx
e2e/a11y/pages/Progress.tsx
e2e/a11y/pages/ProgressTracker.tsx
e2e/a11y/pages/RadioGroup.tsx
e2e/a11y/pages/Rating.tsx
e2e/a11y/pages/Select.tsx
e2e/a11y/pages/Slider.tsx
e2e/a11y/pages/Snackbar.tsx
e2e/a11y/pages/Spinner.tsx
e2e/a11y/pages/Stepper.tsx
e2e/a11y/pages/Switch.tsx
e2e/a11y/pages/Tabs.tsx
e2e/a11y/pages/Tag.tsx
e2e/a11y/pages/Textarea.tsx
e2e/a11y/pages/VisuallyHidden.tsx
e2e/a11y/routes/components.ts
e2e/a11y/routes/elements.tsx
packages/components/slider/src/Slider.doc.mdx
packages/components/slider/src/Slider.stories.tsx
public/a11y/a11y-report.json

**TASK**: [SPA-112](https://jira.ets.mpi-internal.com/browse/SPA-112)
We want to complete Playwright+Axe setup.

test: add missing a11y tests for pw 2/2

---

packages/components/dialog/src/DialogContent.styles.tsx

feat(dialog): ensure correct border radius for overflowing content

---

packages/utils/theme/src/defaultThemeDark.ts

I made a mistake while updating the dark theme earlier.

fix(theme-utils): invalid color for main-variant-hovered

---

packages/components/combobox/src/ComboboxContext.tsx
packages/components/combobox/src/tests/withFormField.test.tsx

feat(combobox): ensure input gets focus when corresponding label is clicked

---

e2e/a11y/pages/TextLink.tsx
packages/components/rating/src/Rating.tsx

**TASK**: https://jira.ets.mpi-internal.com/browse/SPA-202
We noticed some a11y issues in our components. We want to fix some, as CI tests will soon become blocking.

fix(rating): fix a11y issues

---

package-lock.json
packages/components/accordion/package.json
packages/components/collapsible/package.json
packages/components/pagination/package.json

**TASK**: [SPA-227](https://jira.ets.mpi-internal.com/browse/SPA-227)
`zag-js` update (`accordion, collapsible, pagination`)

chore: bump zag-js

---

packages/components/pagination/package.json

Seems someone forgot some deps in the Pagination component :stuck_out_tongue_closed_eyes:

fix(pagination): fix omitted pagination deps

---

.storybook/main.js
.storybook/manager.js
.storybook/sb-theming.css
documentation/helpers/ArgTypes/index.tsx
documentation/helpers/ToC/index.tsx

feat: apply dark theme only to story content

---

documentation/GettingStarted.mdx
documentation/helpers/Card/index.tsx

**TASK**: [SPA-352](https://jira.ets.mpi-internal.com/browse/SPA-352)
Design update for readability

docs: updated carddesign of Getting Started section

---

e2e/form/fields/DropdownField.tsx
e2e/form/fields/DropdownMultipleField.tsx
e2e/form/fields/InputField.tsx
e2e/form/index.spec.tsx
e2e/form/index.tsx
e2e/main.tsx
package-lock.json

**TASK**: [SPA-9](https://jira.ets.mpi-internal.com/browse/SPA-9)
We want to cover some cases for Dropdown (and in the future other form components), as implemented within dropdown and dialog components.

feat: adding spark global form for e2e tests

---

package-lock.json
packages/components/accordion/package.json
packages/components/collapsible/package.json
packages/components/pagination/package.json

fix(pagination): bump zag-js dependencies

---

packages/utils/theme/src/defaultTheme.ts
packages/utils/theme/src/defaultThemeDark.ts

feat(theme-utils): update some color tokens based on latest Figma iteration

---

package-lock.json
packages/components/accordion/package.json
packages/components/collapsible/package.json
packages/components/pagination/package.json

Dependabot required update of `zag-js`

chore: zagjs update

---

package-lock.json
package.json

fix: lint-staged@15.3.0

---

packages/components/icon-button/src/IconButton.styles.tsx

fix(icon-button): padding styles

---

packages/utils/theme/src/custom-variants.css
packages/utils/theme/src/theme.css

feat: add "default" custom tailwind variant

---

package-lock.json
packages/components/accordion/package.json
packages/components/collapsible/package.json
packages/components/pagination/package.json

See https://github.com/chakra-ui/zag/releases/tag/%40zag-js%2Faccordion%401.3.1

chore: bump zag.js to v1.3.1

---

packages/components/accordion/src/Accordion.test.tsx

Latest `zag-js` update broke the `Accordion` tests in CI env only.

test(accordion): fix broken CI tests

---

documentation/Tokens.mdx
documentation/helpers/TokenPreview/index.tsx
packages/utils/theme/src/utilities.css

Started page to showcase main spark token.

docs: mvp of token preview docs page

---

.github/workflows/pr-icon-update.yml
.github/workflows/release.yml

`spark-ui-bot` was managed by Adevinta and does not have rights on `leboncoin` org.

ci: updated gh bot

---

.github/workflows/release.yml

Replaced `SA_TOKEN` with `SPARK_SA_TOKEN` in `release` workflow.

chore: updated security access token reference

---

documentation/Tokens.mdx
package-lock.json
package.json

Added documentation about colors semantics and preview.

docs: color semantics and families

---

packages/components/carousel/src/Carousel.stories.tsx
packages/components/scrolling-list/src/ScrollingList.stories.tsx

**TASK**: [SPA-239](https://jira.ets.mpi-internal.com/browse/SPA-239)
**TASK**: [SPA-545](https://jira.ets.mpi-internal.com/browse/SPA-545)
- Stable release: `@spark-ui/carousel`
- Stable release: `@spark-ui/scrolling-list`

feat(carousel): release carousel and scrolling-list packages as stable

---

package-lock.json
package.json
packages/components/alert-dialog/package.json
packages/components/badge/package.json
packages/components/breadcrumb/package.json
packages/components/button/package.json
packages/components/carousel/package.json
packages/components/checkbox/package.json
packages/components/combobox/package.json
packages/components/dialog/package.json
packages/components/drawer/package.json
packages/components/dropdown/package.json
packages/components/icon-button/package.json
packages/components/input/package.json
packages/components/kbd/package.json
packages/components/label/package.json
packages/components/link-box/package.json
packages/components/progress-tracker/package.json
packages/components/progress/package.json
packages/components/radio-group/package.json
packages/components/scrolling-list/package.json
packages/components/skeleton/package.json
packages/components/slider/package.json
packages/components/snackbar/package.json
packages/components/spinner/package.json
packages/components/switch/package.json
packages/components/tabs/package.json
packages/components/tag/package.json
packages/components/text-link/package.json

`class-variance-authority` fix.
https://github.com/joe-bell/cva/releases/tag/v0.7.1

fix: cva 0.7.1

---

.storybook/preview.tsx
packages/utils/theme/src/keyframes.css
src/components/RandomFish.tsx
src/tailwind.css

fix: improved the aquarium

---

package-lock.json
package.json
tsconfig.json

fix: vite 5

---

packages/components/src/combobox/Combobox.doc.mdx
packages/components/src/combobox/Combobox.stories.tsx
packages/components/src/combobox/ComboboxContext.tsx

Reverts leboncoin/spark-web#2667

Revert "fix(components): combobox - sync async options load  with input"

---

packages/components/src/input/InputClearButton.tsx
packages/components/src/textarea/Textarea.doc.mdx
packages/components/src/textarea/Textarea.stories.tsx
packages/components/src/textarea/TextareaClearButton.tsx
packages/components/src/textarea/index.ts

FOR DESIGN REVIEW/PROPOSAL.
- Adding `InputGroup.ClearButton` to the anatomy of `Textarea`

feat(components): clear button on textarea

---

.github/dependabot.yml

ci: ignore groups patterns in dependabot main group

---

.storybook/preview.tsx
documentation/Tokens.mdx
packages/components/src/carousel/Carousel.doc.mdx

- Fixed typo in font tokens display in MDX
- Fixed anatomy display of `Carousel` in MDX
- set `@storybook/addon-a11y` as `manual` (needs a click to be triggered in story view) => it was causing lags and heavy JS computing by triggering `axe-core` once per `Canvas` in every main doc pages (all components).

docs: fixed various typo in docs

---

documentation/contributing/github-actions.mdx

Document GH SECRETS for the repo

docs(cli-utils): documentation of GH SECRETS

---

documentation/styling/Animations.mdx
packages/utils/theme/src/animations/keyframes.css
packages/utils/theme/src/animations/ping.css
packages/utils/theme/src/animations/rotate.css
packages/utils/theme/src/animations/shake.css

- Display catalog of animations
- added 3 animations: `rotate`, `shake`, `ping`
https://github.com/user-attachments/assets/1924027b-1b62-465e-9186-464c3bee2111

feat(theme-utils): added rotate, ping, shake to animations
